function getMood(t){return state.moods&&state.moods[t]?state.moods[t].mood:null}function setMood(e,o){if(state.moods||(state.moods={}),state.moods[e]&&state.moods[e].mood===o)return delete state.moods[e],saveState(),void renderMoodSection();state.moods[e]={mood:o,time:Date.now()},saveState(),renderMoodSection(),renderGarden(),toast(t("moodNames")[MOOD_KEYS.indexOf(o)]+" check")}function calculateStreak(){if(!state.moods)return 0;const t=today();let e=0;const o=new Date(t);for(;;){const t=fmtDate(o);if(!state.moods[t])break;e++,o.setDate(o.getDate()-1)}return e}function renderMoodSection(){const e=fmtDate(today()),o=getMood(e);document.getElementById("mood-today-label").textContent=t("moodToday"),document.getElementById("mood-title").textContent=t("moodTitle");const n=document.getElementById("moodPicker");n.innerHTML="",MOOD_EMOJIS.forEach(function(a,d){const s=document.createElement("span");s.className="mood-emoji"+(o===MOOD_KEYS[d]?" picked":""),s.textContent=a,s.title=t("moodNames")[d],s.onclick=function(){setMood(e,MOOD_KEYS[d]),animateWatering()},n.appendChild(s)}),document.getElementById("streakDisplay").style.display="none",document.getElementById("mood-history-label").textContent=t("moodHistoryLabel");const a=document.getElementById("moodHistory");a.innerHTML="";for(let e=6;e>=0;e--){const o=new Date(today());o.setDate(o.getDate()-e);const n=getMood(fmtDate(o)),d=document.createElement("div");d.className="mood-bar",d.style.height=n?"28px":"6px",n&&d.classList.add(n),d.title=n?t("moodNames")[MOOD_KEYS.indexOf(n)]+" "+fmtDate(o):fmtDate(o),a.appendChild(d)}}function renderLoveNote(){
/* Phase 1.9 §一 —— 停用（这里原本渲染一张"每日情书"卡片）。
 *
 * 卡片正文来自 LOVE_NOTES.get()：三语各 50 条、共 150 条硬编码文案，全部是第一人称、
 * 以 Barry 的口吻对 Anđela 示爱——
 *   "Svakog jutra kad otvorim oči, prva misao mi si ti." / "每天睁开眼，第一个想到的就是你。"
 *   "Ti nisi samo moja devojka — ti si moj najbolji prijatelj."
 * 其中两条还直接点名："记住 Barry 爱你——Barry 是对的 😉" / "remember Barry loves you".
 * Barry 从未写过这些字，也无法编辑；卡片只对 Anđela 显示，而且每次启动
 * （applyAllUI 的 connection 组，app.js:1336）都会自动渲染一次。
 *
 * 判据与已删除的 randomThinkingOfYou 完全相同：把人名去掉之后，剩下的仍然是同一句
 * 伪造的内心独白，所以"改写成应用口吻"并不成立——应用无法诚实地宣称"我在想你"。
 * 因此停用整张卡片，而不是重写文案。署名行本就已是应用身份 "— Anđelin Ciklus"，
 * 缺陷从来不在签名，而在正文的语气归属。
 *
 * 原实现见于 8b09bb8 之前；LOVE_NOTES 常量仍留在 js/i18n.js 中且已无任何引用。
 * DOM 节点与 id 全部保留，故既有布局断言不受影响。
 * 由 tests/test-phase19-integrity.js 的 C 段守住，不得以任何署名形式恢复。
 */
var el=document.getElementById("loveNoteCard");
if(el)el.style.display="none";
}function renderForecast(){if("andjela"!==activeProfile)return void(document.getElementById("forecastCard").style.display="none");const e=predict(),o=addDays(today(),1),n=getPhase(o,e);let a="";a="period-on"===n||"period-mid"===n||"period-pred-first"===n||"period-pred"===n?t("forecastPeriod"):"ovulation"===n?t("forecastOvulation"):"follicular"===n?t("forecastFollicular"):"luteal"===n||"fertile"===n?t("forecastLuteal"):t("forecastNormal"),document.getElementById("forecastText").textContent=a,document.getElementById("forecastCard").style.display=""}function animateWatering(){const t=document.getElementById("gardenPlant");t&&(t.style.transform="scale(1.3) rotate(10deg)",t.style.transition="transform .3s cubic-bezier(.22, 1, .36, 1)",["💧","💧","💧"].forEach(function(t,e){setTimeout(function(){const e=document.createElement("span");e.textContent=t,e.style.cssText="position:absolute;font-size:.8rem;animation:dropFall 1s ease-in forwards;z-index:10;pointer-events:none;",e.style.left=30+40*Math.random()+"%",e.style.top="-10px",document.getElementById("gardenCard").appendChild(e),setTimeout(function(){e.remove()},1e3)},150*e)}),setTimeout(function(){t.style.transform="",renderGarden()},600))}function renderGarden(){const e=document.getElementById("gardenPlant");e&&(e.style.transform="",e.style.transition="all .5s cubic-bezier(.22, 1, .36, 1)"),document.getElementById("garden-title").textContent=t("gardenTitle");const o=calculateStreak();let n,a,d;if(0===o?(n="🌰",a=t("gardenState0"),d=""):1===o?(n="🌱",a=t("gardenState1"),d=""):o<=3?(n="🌿",a=t("gardenState3"),d=""):o<=7?(n="🌷",a=t("gardenState7"),d=""):(n="🌸",a=t("gardenStateBloom"),d=""),"andjela"===activeProfile&&o>0){const t=getPhase(today(),predict());t&&t.startsWith("period")?n="🌹":"ovulation"===t?n="🌻":"luteal"===t&&(n="🌷")}document.getElementById("gardenPlant").textContent=n,document.getElementById("gardenMsg").textContent=a,document.getElementById("gardenHint").textContent=d}