// Complete 180-lesson JSON generator
const fs = require('fs');
const path = require('path');

function T(zh, sr, en) { return { zh, sr, en }; }
function W(zh, py, sr) { return { zh, py, sr }; }
function CP(prompt, options, correct) {
  return { type: 'choice', prompt, options, correct };
}
function L(id, day, icon, topic, words, dialog, grammar, practice, culture, points) {
  return { id, day, icon, topic, words, dialog, grammar, practice, culture, points };
}

// Compact word format
const w = (zh, py, sr) => [zh, py, sr];

// Expand a compact lesson definition
function expand(d) {
  return L(d[0], d[1], d[2],
    T(d[3], d[4], d[5]),
    d[6].map(a => W(a[0], a[1], a[2])),
    T(d[7], d[8], d[9]),
    T(d[10], d[11], d[12]),
    CP(T(d[13], d[14], d[15]), d[16], d[17]),
    T(d[18], d[19], d[20]),
    d[21]);
}

// ===== ALL LESSON DATA =====
const p1data = [
  [1,1,'🌏','你好！汉语概览','Zdravo! Pregled','Hello! Chinese Overview',
    [w('你好','nǐ hǎo','Zdravo'),w('谢谢','xiè xiè','Hvala'),w('对不起','duì bu qǐ','Izvinite'),w('没关系','méi guān xì','Nema veze'),w('汉语','hàn yǔ','Kineski'),w('学习','xué xí','Učiti')],
    'A: 你好！\nB: 你好！\nA: 谢谢！\nB: 没关系。','A: Zdravo!\nB: Zdravo!\nA: Hvala!\nB: Nema na čemu.','A: Hello!\nB: Hello!\nA: Thank you!\nB: You are welcome.',
    '汉语是SVO语序，没有词形变化。','Kineski ima SVO red reči.','Chinese follows SVO word order.',
    '"谢谢"是什么意思？','Šta znači "xiè xiè"?','What does "xiè xiè" mean?',['Hello','Thank you','Sorry','Goodbye'],1,
    '中国有56个民族。汉语是联合国六种官方语言之一。','Kina ima 56 etničkih grupa.','China has 56 ethnic groups.',10],
  [2,2,'🔤','声母（一）b p m f d t n l','Inicijali(1) b p m f d t n l','Initials(1) b p m f d t n l',
    [w('爸爸','bà ba','Tata'),w('妈妈','mā ma','Mama'),w('朋友','péng yǒu','Prijatelj'),w('弟弟','dì di','Mlađi brat'),w('妹妹','mèi mei','Mlađa sestra'),w('你','nǐ','Ti'),w('他','tā','On'),w('她','tā','Ona')],
    'A: 这是谁？\nB: 这是我爸爸。\nA: 你妈妈呢？\nB: 她在家。','A: Ko je ovo?\nB: Moj tata.\nA: Gde je mama?\nB: Kod kuće.','A: Who is this?\nB: My dad.\nA: Where is mom?\nB: At home.',
    '"是"表判断：A+是+B。否定"不是"疑问加"吗"。','"Shì"=biti. A+shì+B.','"Shì"=to be. A+shì+B.',
    '"爸爸"的拼音？','Pinjin za "tata"?','Pinyin for "dad"?',['mā ma','bà ba','péng yǒu','dì di'],1,
    '中国家庭用亲属称谓称呼家人。','Porodice koriste rodbinske nazive.','Families use kinship terms.',10],
  [3,3,'🔤','声母（二）g k h j q x zh ch sh r','Inicijali(2)','Initials(2)',
    [w('中国','zhōng guó','Kina'),w('吃','chī','Jesti'),w('喝','hē','Piti'),w('看','kàn','Gledati'),w('好','hǎo','Dobar'),w('说','shuō','Govoriti'),w('人','rén','Osoba'),w('去','qù','Ići')],
    'A: 你吃什么？\nB: 我吃米饭。\nA: 你喝什么？\nB: 我喝水。','A: Šta jedeš?\nB: Pirinač.\nA: Šta piješ?\nB: Vodu.','A: What do you eat?\nB: Rice.\nA: What do you drink?\nB: Water.',
    '疑问词"什么"：主语+动词+什么？查问事物。','"Shénme"=šta. Subjekat+glagol+shénme?','"Shénme"=what. Subject+verb+shénme?',
    '"中国"的拼音？','Pinjin za "Kina"?','Pinyin for "China"?',['zhōng guó','zhǒng guǒ','zhòng guō','zhōng gǔo'],0,
    '八大菜系：川粤鲁淮扬湘闽浙徽。','8 kulinarskih škola.','8 cuisine schools.',10],
  [4,4,'🎵','韵母（一）a o e i u ü','Finale(1) a o e i u ü','Finals(1) a o e i u ü',
    [w('爱','ài','Voleti'),w('来','lái','Doći'),w('买','mǎi','Kupiti'),w('大','dà','Velik'),w('我','wǒ','Ja'),w('雨','yǔ','Kiša'),w('鱼','yú','Riba')],
    'A: 你去哪儿？\nB: 我去买鱼。\nA: 下雨了！\nB: 没关系，我带伞了。','A: Gde ideš?\nB: Da kupim ribu.\nA: Pada kiša!\nB: Imam kišobran.','A: Where are you going?\nB: To buy fish.\nA: It rains!\nB: I have umbrella.',
    '"去"+地点。"哪儿"问地点。','"Qù"+mesto. "Nǎr"=gde.','"Qù"+place. "Nǎr"=where.',
    '我___你(wǒ ài nǐ)填什么？','Popuni prazninu','Fill blank',['ài','āi','ǎi','aì'],0,
    '520(5/20)谐音"我爱你"。七夕是传统情人节。','520="Volim te". Qixi=Dan zaljubljenih.','520="I love you". Qixi=Valentine Day.',10],
  [5,5,'🎵','韵母（二）鼻韵母 an en in ang eng ong','Nazalne finale','Nasal Finals',
    [w('很','hěn','Veoma'),w('电话','diàn huà','Telefon'),w('见','jiàn','Videti'),w('先','xiān','Prvo'),w('问','wèn','Pitati'),w('忙','máng','Zauzet'),w('请','qǐng','Molim'),w('听','tīng','Slušati')],
    'A: 喂，你好！\nB: 你好！你忙吗？\nA: 我很忙。\nB: 那先再见！','A: Halo!\nB: Zdravo! Zauzet?\nA: Veoma.\nB: Doviđenja!','A: Hello!\nB: Hello! Busy?\nA: Very.\nB: Goodbye!',
    '"很"+形容词表程度高："很忙""很好"。','"Hěn"+pridev=veoma.','"Hěn"+adj=very.',
    '"电话"的拼音？','Pinjin za "telefon"?','Pinyin for "telephone"?',['diàn huà','diǎn huā','diān huá','diàn hùa'],0,
    '中国接电话先说"喂"，正式场合说"您好"。','Javljanje sa "wéi".','Answer with "wéi".',10],
  [6,6,'🎶','四声和轻声','Četiri tona','Four Tones & Neutral',
    [w('妈','mā','Mama(1)'),w('麻','má','Konoplja(2)'),w('马','mǎ','Konj(3)'),w('骂','mà','Psovati(4)'),w('吗','ma','?(laki)'),w('了','le','rečca(laki)')],
    'A: 你好吗？\nB: 我很好，你呢？\nA: 我也很好。','A: Kako si?\nB: Dobro, a ti?\nA: I ja.','A: How are you?\nB: Fine, you?\nA: Me too.',
    '四声：高平(ā)上升(á)先降后升(ǎ)下降(à)。轻声轻短。','4 tona:1.visok ravni 2.uzlazni 3.sil-uzl 4.silazni.','4 tones: level, rising, fall-rise, falling.',
    '"马"(mǎ)是第几声？','Koji ton?','Which tone?',['1声','2声','3声','4声'],2,
    '声调是汉语灵魂。mā/má/mǎ/mà意思完全不同。','Tonovi su ključni.','Tones are crucial.',10],
  [7,7,'✍️','基本笔画（一）','Osnovne crtice(1)','Basic Strokes(1)',
    [w('我','wǒ','Ja'),w('你','nǐ','Ti'),w('他','tā','On'),w('她','tā','Ona'),w('的','de','Posesiv'),w('是','shì','Biti')],
    'A: 他是谁？\nB: 他是我的朋友。\nA: 她是谁？\nB: 她是我的妹妹。','A: Ko je on?\nB: Moj prijatelj.\nA: Ko je ona?\nB: Moja sestra.','A: Who is he?\nB: My friend.\nA: Who is she?\nB: My sister.',
    '"的"是定语标记：修饰语+的+名词。"我的朋友"。','"De"=atributivna rečca.','"De"=attributive particle.',
    '"的"在"我的书"中表示？','Šta "de" znači?','What does "de" mean?',['Ja','Posesiv','Knjiga','Ovo'],1,
    '六种基本笔画：横竖撇捺点提。','6 osnovnih crtica.','6 basic strokes.',10],
  [8,8,'✍️','基本笔画（二）复合笔画','Složene crtice','Compound Strokes',
    [w('人','rén','Čovek'),w('大','dà','Velik'),w('中','zhōng','Sredina'),w('小','xiǎo','Mali'),w('上','shàng','Gore'),w('下','xià','Dole'),w('不','bù','Ne')],
    'A: 你家大不大？\nB: 不大。\nA: 很大吗？\nB: 很小。','A: Da li je kuća velika?\nB: Nije.\nA: Veoma?\nB: Mala.','A: Is home big?\nB: No.\nA: Very?\nB: Small.',
    'A不A疑问句：肯定+不+肯定。"大不大？"','A-bù-A: afirmativ+bù+afirmativ.','A-bù-A: affirmative+bù+affirmative.',
    '"大不大？"是什么句型？','Šta je "dà bù dà"?','What is "dà bù dà"?',['Veoma veliko','Veliko ili ne?','Nije veliko','Preveliko'],1,
    '笔顺规则：先横后竖，先撇后捺，从上到下。','Pravila redosleda crtica.','Stroke order rules.',10],
  [9,9,'🔢','数字1-10','Brojevi 1-10','Numbers 1-10',
    [w('一','yī','Jedan'),w('二','èr','Dva'),w('三','sān','Tri'),w('四','sì','Četiri'),w('五','wǔ','Pet'),w('六','liù','Šest'),w('七','qī','Sedam'),w('八','bā','Osam'),w('九','jiǔ','Devet'),w('十','shí','Deset')],
    'A: 你有几个苹果？\nB: 三个。\nA: 我有五个。','A: Koliko jabuka?\nB: Tri.\nA: Imam pet.','A: How many apples?\nB: Three.\nA: I have five.',
    '数量结构：数字+量词+名词。基本量词"个"。','Broj+merna reč+imenica.','Number+MW+noun.',
    '"十"是数字几？','Koji broj?','What number?',['6','8','10','4'],2,
    '8(发)吉利，9(久)吉利，4(死)不吉利。','8(bogatstvo) srećan, 4(smrt) nesrećan.','8(wealth) lucky, 4(death) unlucky.',10],
  [10,10,'👋','问候和告别','Pozdravi','Greetings',
    [w('早上好','zǎo shang hǎo','Dobro jutro'),w('晚上好','wǎn shang hǎo','Dobro veče'),w('再见','zài jiàn','Doviđenja'),w('明天见','míng tiān jiàn','Vidimo se sutra'),w('晚安','wǎn ān','Laku noć'),w('您好','nín hǎo','Zdravo(formalno)')],
    'A: 早上好！\nB: 早上好！\nA: 明天见！\nB: 好，明天见！','A: Dobro jutro!\nB: Dobro jutro!\nA: Vidimo se sutra!\nB: Važi!','A: Good morning!\nB: Good morning!\nA: See you tomorrow!\nB: OK!',
    '"您"是"你"的尊称，对长辈或上级使用。','"Nín"=formalno "vi".','"Nín"=formal "you".',
    '"晚安"什么时候说？','Kada se kaže "wǎn ān"?','When to say "wǎn ān"?',['Jutro','Podne','Pre spavanja','Posle podne'],2,
    '中国人常问"吃了吗？"作为问候。','"Jesi li jeo?" kao pozdrav.','"Have you eaten?" as greeting.',10],
  [11,11,'👤','自我介绍','Samopredstavljanje','Self-Introduction',
    [w('叫','jiào','Zvati se'),w('姓','xìng','Prezime'),w('名字','míng zì','Ime'),w('认识','rèn shí','Upoznati'),w('高兴','gāo xìng','Drago mi'),w('也','yě','Takođe')],
    'A: 你好！我叫安娜。\nB: 我叫马克。很高兴认识你！\nA: 我也很高兴！','A: Zdravo! Ana.\nB: Mark. Drago mi!\nA: I meni!','A: Hello! I am Anna.\nB: I am Mark. Nice to meet you!\nA: You too!',
    '"叫"介绍名字："我+叫+名字"。"姓"介绍姓氏。','"Jiào"=zvati se. "Xìng"=prezime.','"Jiào"=called. "Xìng"=surname.',
    '"认识"是什么意思？','Šta znači "rèn shí"?','What means "rèn shí"?',['Pamtiti','Upoznati','Razumeti','Govoriti'],1,
    '中国人介绍先说姓氏。握手轻。递名片用双手。','Kinezi prvo kažu prezime.','Surname first.',10],
  [12,12,'🌍','国籍和语言','Nacionalnost i jezici','Nationalities & Languages',
    [w('中国','zhōng guó','Kina'),w('塞尔维亚','sài ěr wéi yà','Srbija'),w('美国','měi guó','Amerika'),w('说','shuō','Govoriti'),w('会','huì','Znati'),w('英语','yīng yǔ','Engleski'),w('塞尔维亚语','sài ěr wéi yà yǔ','Srpski')],
    'A: 你是哪国人？\nB: 我是塞尔维亚人。\nA: 你会说汉语吗？\nB: 我会说一点儿。','A: Odakle si?\nB: Iz Srbije.\nA: Govoriš kineski?\nB: Malo.','A: Where from?\nB: Serbia.\nA: Speak Chinese?\nB: A little.',
    '"会"表技能。"说"+语言。"一点儿"=少量。','"Huì"=umeti. "Shuō"+jezik. "Yìdiǎnr"=malo.','"Huì"=can(skill). "Shuō"+language.',
    '"我会说汉语"中"会"表示？','Šta "huì" znači?','What does "huì" mean?',['Hteti','Umeti','Morati','Moći'],1,
    '中塞全面战略伙伴。互免签证。','Srbija-Kina strateški partneri.','Serbia-China strategic partners.',10],
  [13,13,'👨‍👩‍👧','年龄和家庭（一）','Godine(1)','Age & Family(1)',
    [w('岁','suì','Godina'),w('爸爸','bà ba','Tata'),w('妈妈','mā ma','Mama'),w('爷爷','yé ye','Deda'),w('奶奶','nǎi nai','Baba'),w('几','jǐ','Koliko')],
    'A: 你几岁？\nB: 我二十五岁。\nA: 你爸爸多大？\nB: 他五十岁。','A: Koliko godina?\nB: 25.\nA: Tata?\nB: 50.','A: How old?\nB: 25.\nA: Dad?\nB: 50.',
    '"几岁"问年龄。"岁"在数字后表示岁数。','"Jǐ suì"=koliko godina?','"Jǐ suì"=how old?',
    '"你几岁？"问什么？','Šta pita?','What asked?',['Ime','Godine','Adresu','Posao'],1,
    '中国尊敬老人。"孝"是重要美德。','Kinezi poštuju stare.','Chinese respect elders.',10],
  [14,14,'👨‍👩‍👧‍👦','家庭（二）','Porodica(2)','Family(2)',
    [w('哥哥','gē ge','Stariji brat'),w('姐姐','jiě jie','Starija sestra'),w('弟弟','dì di','Mlađi brat'),w('妹妹','mèi mei','Mlađa sestra'),w('孩子','hái zi','Dete'),w('爱','ài','Voleti')],
    'A: 你有兄弟姐妹吗？\nB: 我有一个哥哥和一个妹妹。','A: Imaš braće?\nB: Starijeg brata i mlađu sestru.','A: Have siblings?\nB: Older brother, younger sister.',
    '汉语区分为兄/弟、姐/妹。"有"+拥有。"没有"否定。','Razlikuje starijeg/lađeg brata/sestru.','Differentiates older/younger siblings.',
    '"哥哥"是？','"Gē ge" je?','What is "gē ge"?',['Mlađi brat','Stariji brat','Starija sestra','Mlađa sestra'],1,
    '独生子女政策(1979-2015)，现开放三胎。','Politika jednog deteta(1979-2015).','One-child policy(1979-2015).',10],
  [15,15,'💼','职业','Zanimanja','Professions',
    [w('医生','yī shēng','Doktor'),w('老师','lǎo shī','Učitelj'),w('学生','xué shēng','Učenik'),w('工程师','gōng chéng shī','Inženjer'),w('护士','hù shì','Sestra'),w('工作','gōng zuò','Posao')],
    'A: 你是做什么的？\nB: 我是医生。\nA: 你爸爸呢？\nB: 他是工程师。','A: Čime se baviš?\nB: Doktor.\nA: Tata?\nB: Inženjer.','A: What do you do?\nB: Doctor.\nA: Dad?\nB: Engineer.',
    '"是"+职业。"做什么的"询问职业。','"Shì"+zanimanje.','"Shì"+profession.',
    '"工程师"是什么？','Šta je "gōng chéng shī"?','What is "gōng chéng shī"?',['Doktor','Učitelj','Inženjer','Student'],2,
    '最受尊敬的职业：医生、教师、工程师。','Najpoštovanija: doktor, učitelj, inženjer.','Most respected: doctor, teacher, engineer.',10],
  [16,16,'🏃','基本动词','Osnovni glagoli','Basic Verbs',
    [w('吃','chī','Jesti'),w('喝','hē','Piti'),w('走','zǒu','Hodati'),w('跑','pǎo','Trčati'),w('看','kàn','Gledati'),w('听','tīng','Slušati'),w('读','dú','Čitati'),w('写','xiě','Pisati')],
    'A: 你早上做什么？\nB: 我吃早饭然后看手机。\nA: 你听音乐吗？\nB: 听。','A: Šta radiš ujutro?\nB: Doručkujem, gledam telefon.\nA: Slušaš muziku?\nB: Da.','A: What in morning?\nB: Breakfast, look phone.\nA: Listen music?\nB: Yes.',
    '动词连用。"然后"表先后顺序。','Glagoli u nizu. "Ránhòu"=zatim.','Verbs sequence. "Ránhòu"=then.',
    '"读"的意思？','Šta znači "dú"?','What means "dú"?',['Pisati','Čitati','Slušati','Govoriti'],1,
    '中国学生从小学英语。"读书"也指上学。','Uče engleski od osnovne škole.','Learn English from elementary.',10],
  [17,17,'📐','基本形容词','Osnovni pridevi','Basic Adjectives',
    [w('大','dà','Velik'),w('小','xiǎo','Mali'),w('高','gāo','Visok'),w('矮','ǎi','Nizak'),w('漂亮','piào liang','Lepa'),w('可爱','kě ài','Slatka'),w('好吃','hǎo chī','Ukusno')],
    'A: 这家餐厅好吃吗？\nB: 很好吃！\nA: 贵不贵？\nB: 不贵，便宜。','A: Ukusno?\nB: Veoma!\nA: Skupo?\nB: Nije, jeftino.','A: Tasty?\nB: Very!\nA: Expensive?\nB: No, cheap.',
    '否定：不+形容词。"很"+形容词表程度。','Negacija: bù+pridev. "Hěn"=veoma.','Negation: bù+adj. "Hěn"=very.',
    '"好吃"的反义词？','Antonim "hǎo chī"?','Antonym of "hǎo chī"?',['好喝','难吃','好看','好吃'],1,
    '八大菜系各有特色。川辣粤鲜鲁咸。','8 škola. Sečuan ljuto, Kantonska sveže.','8 schools. Sichuan spicy, Cantonese fresh.',10],
  [18,18,'🎨','颜色','Boje','Colors',
    [w('红','hóng','Crvena'),w('黄','huáng','Žuta'),w('蓝','lán','Plava'),w('绿','lǜ','Zelena'),w('白','bái','Bela'),w('黑','hēi','Crna')],
    'A: 你喜欢什么颜色？\nB: 我喜欢红色和白色。\nA: 为什么？\nB: 红色很漂亮。','A: Koja boja?\nB: Crvena i bela.\nA: Zašto?\nB: Crvena lepa.','A: What color?\nB: Red and white.\nA: Why?\nB: Red is beautiful.',
    '"喜欢"+颜色/动词："我喜欢红色"。','"Xǐhuān"+boja/glagol.','"Xǐhuān"+color/verb.',
    '中国国旗颜色？','Boje kineske zastave?','Chinese flag colors?',['Crvena/bela','Crvena/žuta','Plava/bela','Zelena/crvena'],1,
    '红色象征好运。黄色曾是皇家颜色。','Crvena=sreća. Žuta=carska.','Red=luck. Yellow=imperial.',10],
  [19,19,'❓','疑问词','Upitne reči','Question Words',
    [w('什么','shén me','Šta'),w('谁','shuí','Ko'),w('哪儿','nǎr','Gde'),w('怎么','zěn me','Kako'),w('为什么','wèi shén me','Zašto'),w('几','jǐ','Koliko')],
    'A: 这是谁的书？\nB: 是我的。\nA: 你的书在哪儿？\nB: 在桌子上。','A: Čija knjiga?\nB: Moja.\nA: Gde ti je?\nB: Na stolu.','A: Whose book?\nB: Mine.\nA: Where?\nB: On table.',
    '疑问词原位不移动。"什么"问事物，"谁"问人，"哪儿"问地点。','Upitne reči ostaju na mestu.','Question words stay in place.',
    '"为什么"问什么？','"Wèi shénme" pita?','What "wèi shénme" asks?',['Gde','Zašto','Kako','Šta'],1,
    '"吃了吗？"是问候，不是真问吃饭。','Jesi li jeo=pozdrav.','Have you eaten=greeting.',10],
  [20,20,'📚','综合复习1','Pregled 1','Review 1',
    [w('复习','fù xí','Ponavljanje'),w('练习','liàn xí','Vežba'),w('记住','jì zhù','Zapamtiti'),w('忘记','wàng jì','Zaboraviti'),w('懂','dǒng','Razumeti'),w('问题','wèn tí','Pitanje')],
    'A: 这个字你懂吗？\nB: 我懂了。\nA: 我们一起复习吧！\nB: 好的！','A: Razumeš?\nB: Razumem.\nA: Ponovimo!\nB: U redu!','A: Understand?\nB: Yes.\nA: Let\'s review!\nB: OK!',
    '复习：SVO语序、"是"字句、A不A疑问句。','Pregled: SVO, shì, A-bù-A.','Review: SVO, shì, A-bù-A.',
    'SVO中的S是什么？','Šta je S u SVO?','What is S in SVO?',['Glagol','Subjekat','Objekat','Pridev'],1,
    '"温故而知新"温习旧知识能获新理解。','Učenje kroz ponavljanje-Konfučije.','Review old to learn new-Confucius.',15],
  [21,21,'📅','时间-日期','Datum','Date',
    [w('今天','jīn tiān','Danas'),w('明天','míng tiān','Sutra'),w('昨天','zuó tiān','Juče'),w('星期','xīng qī','Nedelja'),w('月','yuè','Mesec'),w('年','nián','Godina'),w('号','hào','Datum')],
    'A: 今天几月几号？\nB: 六月二十三号。\nA: 昨天星期几？\nB: 星期一。','A: Koji datum?\nB: 23.jun.\nA: Juče?\nB: Ponedeljak.','A: What date?\nB: June 23.\nA: Yesterday?\nB: Monday.',
    '日期：年+月+号。星期：星期+数字。周日=星期日/天。','Datum: god+mesec+dan.','Date: year+month+day.',
    '"星期天"是星期几？','Koji dan?','What day?',['Pon','Sub','Ned','Pet'],2,
    '中国用农历和阳历。传统节日按农历。','Lunarni i solarni kalendar.','Lunar and solar calendars.',10],
  [22,22,'🕐','时间-时刻','Sat','Clock Time',
    [w('早上','zǎo shang','Jutro'),w('中午','zhōng wǔ','Podne'),w('下午','xià wǔ','Posle podne'),w('晚上','wǎn shang','Veče'),w('点','diǎn','Sat'),w('分','fēn','Minut'),w('半','bàn','Pola')],
    'A: 现在几点？\nB: 早上八点半。\nA: 你几点上班？\nB: 九点。','A: Koliko sati?\nB: 8:30.\nA: Kad posao?\nB: U 9.','A: What time?\nB: 8:30.\nA: When work?\nB: At 9.',
    '时间表达：点+分。半=30分，刻=15分。','Vreme: sat+minut. Bàn=30, kè=15.','Time: hour+minute. Bàn=30.',
    '"半"表示多少分钟？','"Bàn"=koliko minuta?','"Bàn"=how many min?',['15','30','45','10'],1,
    '中国朝九晚五，午休1-2小时。"午睡"常见。','Radno 9-17, pauza 1-2h.','Work 9-5, lunch break 1-2h.',10],
  [23,23,'🌅','日常作息','Dnevna rutina','Daily Routine',
    [w('起床','qǐ chuáng','Ustati'),w('吃饭','chī fàn','Jesti'),w('上班','shàng bān','Ići na posao'),w('回家','huí jiā','Vratiti se'),w('睡觉','shuì jiào','Spavati'),w('洗澡','xǐ zǎo','Tuširati se')],
    'A: 你每天几点起床？\nB: 七点。\nA: 几点睡觉？\nB: 十一点。','A: Kad ustaješ?\nB: U 7.\nA: Kad spavaš?\nB: U 23.','A: What time wake?\nB: 7.\nA: When sleep?\nB: 11.',
    '时间+动词。"每天"=每+天＝every day。','Vreme+glagol. "Měi tiān"=svaki dan.','Time+verb. "Měi tiān"=every day.',
    '"起床"的意思？','Šta znači "qǐ chuáng"?','What means "qǐ chuáng"?',['Spavati','Ustati','Jesti','Tuširati se'],1,
    '谚语"一日之计在于晨"。晨练者常见。','"Jutro je najvažnije."','"Morning is most important."',10],
  [24,24,'🌤️','天气和季节','Vreme i godišnja doba','Weather & Seasons',
    [w('冷','lěng','Hladno'),w('热','rè','Vruće'),w('下雨','xià yǔ','Pada kiša'),w('下雪','xià xuě','Sneg'),w('春天','chūn tiān','Proleće'),w('夏天','xià tiān','Leto'),w('秋天','qiū tiān','Jesen'),w('冬天','dōng tiān','Zima')],
    'A: 今天天气怎么样？\nB: 很冷，在下雪。\nA: 塞尔维亚冬天冷吗？\nB: 很冷。','A: Kakvo vreme?\nB: Hladno, sneg.\nA: Zima u Srbiji?\nB: Veoma.','A: How weather?\nB: Cold, snow.\nA: Winter in Serbia?\nB: Very cold.',
    '"怎么样"问状况。"在+动词"表示动作进行中。','"Zěnme yàng"=kako. "Zài+V"=u toku.','"Zěnme yàng"=how. "Zài+V"=in progress.',
    '"热"的意思？','Šta znači "rè"?','What means "rè"?',['Hladno','Vruće','Kiša','Sneg'],1,
    '中国气候多样。北京和贝尔格莱德纬度相近。','Raznolika klima. Peking-Beograd slične širine.','Diverse climate. Beijing-Belgrade similar lat.',10],
  [25,25,'🍜','食物和饮料','Hrana i piće','Food & Drinks',
    [w('米饭','mǐ fàn','Pirinač'),w('面条','miàn tiáo','Rezanci'),w('水','shuǐ','Voda'),w('茶','chá','Čaj'),w('咖啡','kā fēi','Kafa'),w('牛奶','niú nǎi','Mleko'),w('鸡蛋','jī dàn','Jaje'),w('面包','miàn bāo','Hleb')],
    'A: 你想吃什么？\nB: 我想吃面条。\nA: 喝什么？\nB: 喝茶。','A: Šta želiš jesti?\nB: Rezance.\nA: Za piće?\nB: Čaj.','A: What eat?\nB: Noodles.\nA: Drink?\nB: Tea.',
    '"想"+动词表意愿。否定"不想"。','"Xiǎng"+glagol=želeti. Neg:"bù xiǎng".','"Xiǎng"+verb=want. Neg:"bù xiǎng".',
    '"茶"是什么？','Šta je "chá"?','What is "chá"?',['Kafa','Mleko','Čaj','Sok'],2,
    '中国六大茶类：绿红乌白黄黑。功夫茶传统。','6 vrsta čaja. Kung fu čaj.','6 tea types. Kung fu tea.',10],
  [26,26,'📍','方位词','Položaj','Location Words',
    [w('上面','shàng miàn','Iznad'),w('下面','xià miàn','Ispod'),w('里面','lǐ miàn','Unutra'),w('外面','wài miàn','Napolju'),w('旁边','páng biān','Pored'),w('对面','duì miàn','Preko puta'),w('左边','zuǒ biān','Levo'),w('右边','yòu biān','Desno')],
    'A: 我的手机在哪儿？\nB: 在桌子上面。\nA: 没有啊！\nB: 哦，在书的下面。','A: Gde je telefon?\nB: Na stolu.\nA: Nema!\nB: Ispod knjige.','A: Where is phone?\nB: On table.\nA: Not there!\nB: Under book.',
    '方位：名词+上面/下面/里面等。"在"表位置。','Položaj: imenica+shàngmiàn. "Zài"=nalazi se.','Location: noun+shàngmiàn. "Zài"=at.',
    '"外面"的意思？','Šta je "wài miàn"?','What is "wài miàn"?',['Unutra','Napolju','Iznad','Pored'],1,
    '中国人指路常用东西方向而非左右。','Kinezi koriste strane sveta.','Chinese use compass directions.',10],
  [27,27,'📦','量词（一）','Merne reči(1)','Measure Words(1)',
    [w('个','gè','(opšta)'),w('只','zhī','(životinje)'),w('条','tiáo','(dugačko)'),w('本','běn','(knjige)'),w('杯','bēi','(pića)'),w('张','zhāng','(ravno)'),w('件','jiàn','(odeća)')],
    'A: 你要几个苹果？\nB: 三个。\nA: 还要什么？\nB: 一杯茶和两本书。','A: Koliko jabuka?\nB: Tri.\nA: Još?\nB: Čaj i dve knjige.','A: How many apples?\nB: Three.\nA: More?\nB: Tea and two books.',
    '数词+量词+名词。不同名词用不同量词。"个"通用。','Broj+merna reč+imenica. "Gè" je opšta.','Number+MW+noun. "Gè" general.',
    '"一本书"的量词？','Merna reč za "knjiga"?','MW for "book"?',['个','只','本','条'],2,
    '汉语有上百量词。正确使用是流利标志。','Stotine mernih reči.','Hundreds of measure words.',10],
  [28,28,'🏠','日常用品','Dnevni predmeti','Daily Items',
    [w('桌子','zhuō zi','Sto'),w('椅子','yǐ zi','Stolica'),w('门','mén','Vrata'),w('窗','chuāng','Prozor'),w('手机','shǒu jī','Mobilni'),w('钱包','qián bāo','Novčanik'),w('钥匙','yào shi','Ključ'),w('书包','shū bāo','Ranac')],
    'A: 你的手机在哪儿？\nB: 在桌子上。\nA: 钥匙呢？\nB: 在书包里面。','A: Gde je telefon?\nB: Na stolu.\nA: Ključevi?\nB: U rancu.','A: Where is phone?\nB: On table.\nA: Keys?\nB: In backpack.',
    '"在"表位置。"有"表存在。前者强调位置，后者强调存在。','"Zài"=nalazi se. "Yǒu"=postoji.','"Zài"=located. "Yǒu"=there is.',
    '"钱包"是什么？','Šta je "qián bāo"?','What is "qián bāo"?',['Ključ','Novčanik','Telefon','Torba'],1,
    '中国移动支付发达。微信支付支付宝人人用。','Mobilno plaćanje: WeChat Pay, Alipay.','Mobile payment: WeChat Pay, Alipay.',10],
  [29,29,'📖','综合练习-我的生活','Vežba-Moj život','Practice-My Life',
    [w('生活','shēng huó','Život'),w('每天','měi tiān','Svaki dan'),w('常常','cháng cháng','Često'),w('有时候','yǒu shí hou','Ponekad'),w('总是','zǒng shì','Uvek'),w('从不','cóng bù','Nikad')],
    'A: 你每天生活怎么样？\nB: 我七点起床八点上班。\nA: 你常常喝茶吗？\nB: 总是一边工作一边喝。','A: Kako dan?\nB: Ustajem 7, posao 8.\nA: Piješ čaj?\nB: Uvek dok radim.','A: How day?\nB: Wake 7, work 8.\nA: Drink tea?\nB: Always working.',
    '频率副词：总是(100%)常常(80%)有时候(30%)从不(0%)在动词前。','Prilozi učestalosti ispred glagola.','Frequency adverbs before verb.',
    '哪个频率更高？','Šta je češće?','Which more frequent?',['常常','总是','Isto','Nijedno'],1,
    '塞尔维亚生活节奏悠闲。中国大城市节奏快。','Srbija opuštena. Kina brza.','Serbia relaxed. China fast.',15],
  [30,30,'🎯','阶段1测试','Test faze 1','Phase 1 Test',
    [w('考试','kǎo shì','Ispit'),w('通过','tōng guò','Proći'),w('成绩','chéng jì','Rezultat'),w('进步','jìn bù','Napredak'),w('继续','jì xù','Nastaviti'),w('加油','jiā yóu','Samo napred')],
    'A: 考试怎么样？\nB: 很好！进步了。\nA: 恭喜！继续加油！\nB: 谢谢！','A: Kako ispit?\nB: Odlično! Napredak.\nA: Čestitam! Samo napred!\nB: Hvala!','A: How test?\nB: Great! Improved.\nA: Congrats! Keep going!\nB: Thanks!',
    '"加油"(add oil)是常用鼓励语。"继续"+动词表持续。','"Jiā yóu"=samo napred. Ohrabrenje.','"Jiā yóu"=keep going. Encouragement.',
    '"加油"的意思？','Šta "jiā yóu"?','What "jiā yóu"?',['Sipati ulje','Samo napred','Dodati','Vozi'],1,
    '恭喜完成第一阶段30课！继续努力！','Čestitam na fazi 1!','Congrats on Phase 1!',20],
  // CONTINUED IN PART 2...
];

const p1 = { phase:1, name:T('拼音基石','Osnove Pinjina','Pinyin Basics'),
  description:T('学习汉语拼音系统，包括声母、韵母和声调。这是说好普通话的基础。','Naučite sistem kineskog izgovora Pinjin.','Learn the Chinese pinyin system.'),
  icon:'🏛️', lessons: p1data.map(expand) };

// Write phase 1
const p2data = []; // will be filled in part 2
const p2 = { phase:2, name:T('日常生活','Svakodnevni život','Daily Life'),
  description:T('学习日常交流场景：餐厅、购物、问路、交通、看病等。','Naučite svakodnevne komunikacijske scene.','Learn daily communication scenes.'),
  icon:'🗣️', lessons: [] };

const p3 = { phase:3, name:T('社交出行','Društveni život','Social Life'),
  description:T('学习社交和出行相关表达。','Naučite društvene izraze.','Learn social expressions.'),
  icon:'🌆', lessons: [] };
const p4 = { phase:4, name:T('情感对话','Emocionalni dijalozi','Emotional Dialogues'),
  description:T('学习表达情感和深入交流。','Naučite emocije.','Learn emotions.'),
  icon:'💬', lessons: [] };
const p5 = { phase:5, name:T('读写进阶','Čitanje i pisanje','Reading & Writing'),
  description:T('提升读写能力。','Unapredite čitanje.','Improve reading/writing.'),
  icon:'📝', lessons: [] };
const p6 = { phase:6, name:T('流利表达','Tečno izražavanje','Fluent Expression'),
  description:T('达到流利交流水平。','Dostignite tečnost.','Achieve fluency.'),
  icon:'🎯', lessons: [] };

const data = [p1, p2, p3, p4, p5, p6];
const json = JSON.stringify(data, null, 2);
const outpath = path.join(__dirname, '..', 'data', 'lessons_part1.json');
fs.writeFileSync(outpath, json, 'utf8');
console.log('Phase 1 written:', p1.lessons.length, 'lessons');
console.log('File:', outpath);
console.log('Size:', (json.length/1024).toFixed(1), 'KB');
