// Phase 3-6 lesson data (compact format)
const w = (zh,py,sr)=>({zh,py,sr});

const p3data = [
  // Phase 3: Social Life (61-90)
  [61,61,'🏠','租房','Iznajmljivanje stana','Renting',
    [w('房子','fáng zi','Stan'),w('租房','zū fáng','Iznajmiti'),w('房东','fáng dōng','Stanodavac'),w('房租','fáng zū','Kirija'),w('押金','yā jīn','Depozit'),w('合同','hé tong','Ugovor')],
    'A: 我想租房。\nB: 一个月三千块。\nA: 押金多少？\nB: 一个月房租。','A: Želim iznajmiti stan.\nB: 3000/mesec.\nA: Depozit?\nB: Jedna kirija.','A: I want to rent.\nB: 3000/month.\nA: Deposit?\nB: One month rent.',
    '"想"+动词表示意愿。"多少"问数量。','"Xiǎng"+glagol=želeti. "Duōshao"=koliko.','"Xiǎng"+verb=want. "Duōshao"=how much.',
    '"房东"是谁？','Ko je "fáng dōng"?','Who is "fáng dōng"?',['Stanar','Stanodavac','Agent','Policajac'],1,
    '中国租房常用APP：贝壳找房、自如。押一付三常见。','Aplikacije za iznajmljivanje: Beike, Ziru.','Rental apps: Beike, Ziru. Deposit+3 months rent.',10],
  [62,62,'💼','求职','Traženje posla','Job Hunting',
    [w('工作','gōng zuò','Posao'),w('面试','miàn shì','Intervju'),w('简历','jiǎn lì','CV'),w('工资','gōng zī','Plata'),w('经验','jīng yàn','Iskustvo'),w('应聘','yìng pìn','Prijaviti')],
    'A: 我来应聘。\nB: 请给我你的简历。\nA: 这是我的简历。\nB: 明天来面试。','A: Prijavljujem se.\nB: Dajte CV.\nA: Izvolite.\nB: Dođite sutra na intervju.','A: I\'m applying.\nB: Give me your CV.\nA: Here it is.\nB: Come for interview tomorrow.',
    '"来"+动词表即将做。"给+我+物品"表递。','"Lái"+glagol. "Gěi wǒ"+stvar.','"Lái"+verb. "Gěi wǒ"+thing.',
    '"面试"是什么意思？','Šta "miàn shì"?','What "miàn shì"?',['Test','Intervju','Posao','Ugovor'],1,
    '中国常用招聘网站：智联招聘、BOSS直聘、前程无忧。','Kineski sajtovi za posao: Zhilian, BOSS, 51Job.','Chinese job sites: Zhilian, BOSS, 51Job.',10],
  [63,63,'📱','社交媒体','Društvene mreže','Social Media',
    [w('微信','wēi xìn','WeChat'),w('微博','wēi bó','Weibo'),w('朋友圈','péng yǒu quān','Moments'),w('点赞','diǎn zàn','Lajkati'),w('评论','píng lùn','Komentar'),w('关注','guān zhù','Pratiti')],
    'A: 你有微信吗？\nB: 有，加个好友吧。\nA: 好，我扫你。\nB: 好了！','A: Imaš WeChat?\nB: Da, dodaj me.\nA: Skeniraj me.\nB: Gotovo!','A: Have WeChat?\nB: Yes, add me.\nA: Scan me.\nB: Done!',
    '"有...吗？"问有否。"加好友"=add friend。"扫"=scan QR。','"Yǒu...ma?"=imaš li? "Jiā hǎo yǒu"=dodaj.','"Yǒu...ma?"=have? "Jiā hǎo yǒu"=add friend.',
    '"微信"是什么？','Šta "wēi xìn"?','What "wēi xìn"?',['App za poruke','Igra','Pošta','Muzika'],0,
    '微信是中国最重要的社交app，集聊天支付于一体。','WeChat je najvažnija kineska aplikacija.','WeChat is the most important Chinese app.',10],
  [64,64,'🌐','网络用语','Internet žargon','Internet Slang',
    [w('上网','shàng wǎng','Internet'),w('点赞','diǎn zàn','Lajk'),w('粉丝','fěn sī','Fanovi'),w('网红','wǎng hóng','Influenser'),w('视频','shì pín','Video'),w('直播','zhí bō','Uživo')],
    'A: 你上网做什么？\nB: 看视频。\nA: 你喜欢哪个网红？\nB: 李佳琦。','A: Šta radiš na internetu?\nB: Gledam video.\nA: Koji influenser?\nB: Li Jiaqi.','A: What do you do online?\nB: Watch videos.\nA: Which influencer?\nB: Li Jiaqi.',
    '"上+网/班/学"=go to。','"Shàng"+net/posao/škola.','"Shàng"+net/work/school.',
    '"网红"的意思？','Šta "wǎng hóng"?','What "wǎng hóng"?',['Crveni','Influenser','Haker','Igrač'],1,
    '中国网红经济巨大。李佳琦直播带货销售额惊人。','Kineski influenseri ogromni. Li Jiaqi prodaje milijarde.','Chinese influencer economy huge.',10],
  [65,65,'💑','约会恋爱','Ljubav i dejting','Dating',
    [w('约会','yuē huì','Sastanak'),w('喜欢','xǐ huān','Sviđa'),w('男朋友','nán péng yǒu','Dečko'),w('女朋友','nǚ péng yǒu','Devojka'),w('结婚','jié hūn','Venčati'),w('恋爱','liàn ài','Ljubav')],
    'A: 你有女朋友吗？\nB: 有，在一起两年了。\nA: 打算结婚吗？\nB: 还在考虑。','A: Imaš devojku?\nB: Da, dve godine.\nA: Planirate venčanje?\nB: Još razmišljamo.','A: Have girlfriend?\nB: Yes, two years.\nA: Plan marriage?\nB: Still thinking.',
    '"在+一起"=be together。"打算"+动词=plan to。','"Zài+yìqǐ"=biti zajedno. "Dǎsuàn"+glagol=planirati.','"Zài+yìqǐ"=be together. "Dǎsuàn"=plan to.',
    '"男朋友"英文？','Engleski "nán péng yǒu"?','English "nán péng yǒu"?',['Girlfriend','Boyfriend','Friend','Husband'],1,
    '中国年轻人越来越晚婚。大城市平均30岁结婚。','Kinezi sve kasnije stupaju u brak.','Chinese marry later, avg 30 in big cities.',10],
  [66,66,'⏳','时间顺序表达','Vremenski redosled','Time Sequence',
    [w('先','xiān','Prvo'),w('然后','rán hòu','Zatim'),w('最后','zuì hòu','Na kraju'),w('以前','yǐ qián','Pre'),w('以后','yǐ hòu','Posle'),w('同时','tóng shí','Istovremeno')],
    'A: 你每天做什么？\nB: 先起床然后吃早饭最后去上班。\nA: 以前几点起床？\nB: 以前八点现在七点。','A: Dnevna rutina?\nB: Ustanem, doručkujem, idem.\nA: Pre?\nB: U 8, sad u 7.','A: Daily routine?\nB: Wake, breakfast, go.\nA: Before?\nB: At 8, now 7.',
    '时间顺序：先+动作1+然后+动作2+最后+动作3。','Redosled: xiān+ránhòu+zuìhòu.','Sequence: xiān+then+finally.',
    '"然后"表示什么关系？','Šta "ránhòu"?','What "ránhòu"?',['Razlog','Vremenski red','Suprotnost','Uslov'],1,
    '汉语时间顺序表达与塞尔维亚语类似。时间词在句首或动词前。','Vremenski izrazi slični srpskom. Vreme na početku rečenice.','Time expressions similar to Serbian.',10],
  [67,67,'🔗','因果关系','Uzrok-posledica','Cause-Effect',
    [w('因为','yīn wèi','Zato što'),w('所以','suǒ yǐ','Zato'),w('为了','wèi le','Da bi'),w('由于','yóu yú','Usled'),w('因此','yīn cǐ','Stoga'),w('结果','jié guǒ','Rezultat')],
    'A: 你为什么学汉语？\nB: 因为我喜欢中国文化。\nA: 所以你来中国了？\nB: 对所以我在这里。','A: Zašto učiš kineski?\nB: Zato što volim kinesku kulturu.\nA: Zato si došao u Kinu.\nB: Da.','A: Why learn Chinese?\nB: Because I like Chinese culture.\nA: So you came to China?\nB: Yes, so I\'m here.',
    '"因为...所以..."=because...so...。','"Yīnwèi...suǒyǐ..."=zato što...zato...','"Yīnwèi...suǒyǐ..."=because...so...',
    '"因为"和"所以"一起用吗？','Da li idu zajedno?','Do they go together?',['Samo 因为','Samo 所以','Oba','Nijedno'],2,
    '"因为...所以..."是最常用的因果关联词。塞尔维亚语也类似。','"Yīnwèi...suǒyǐ..." najčešći uzročni veznici.','Most common causal conjunctions.',10],
  [68,68,'🔄','转折让步','Kontrast i ustupak','Contrast & Concession',
    [w('但是','dàn shì','Ali'),w('可是','kě shì','Međutim'),w('虽然','suī rán','Iako'),w('不过','bú guò','Ipak'),w('尽管','jǐn guǎn','Uprkos'),w('却','què','Međutim')],
    'A: 汉语难吗？\nB: 虽然难但是很有意思。\nA: 语法难不难？\nB: 语法不难可是声调很难。','A: Kineski težak?\nB: Iako težak, zanimljiv.\nA: Gramatika?\nB: Nije teška, ali tonovi jesu.','A: Chinese hard?\nB: Although hard, interesting.\nA: Grammar?\nB: Not hard, but tones are.',
    '"虽然...但是..."=although...but...。','"Suīrán...dànshì..."=iako...ali...','"Suīrán...dànshì..."=although...but...',
    '"虽然...但是..."用几个关联词？','Koliko veznika?','How many conjunctions?',['1','2','3','0'],1,
    '汉语"虽然...但是..."成对使用。塞尔维亚语iako...ali类似。','Suīrán...dànshì" par. Slično srpskom.','Paired conjunction. Similar to Serbian.',10],
  [69,69,'🔀','条件假设','Uslovi i pretpostavke','Conditions',
    [w('如果','rú guǒ','Ako'),w('就','jiù','Onda'),w('要是','yào shì','Ako(ako)'),w('那么','nà me','Tada'),w('不然','bù rán','Inače'),w('否则','fǒu zé','U suprotnom')],
    'A: 如果明天下雨还去吗？\nB: 如果下雨就不去了。\nA: 要是出太阳呢？\nB: 那就去！','A: Ako sutra pada kiša?\nB: Onda ne idemo.\nA: Ako sunce?\nB: Onda idemo!','A: If rain tomorrow?\nB: Then no go.\nA: If sunny?\nB: Then go!',
    '"如果...就..."=if...then...。条件在前结果在后。','"Rúguǒ...jiù..."=ako...onda...','"Rúguǒ...jiù..."=if...then...',
    '"如果"和"就"？','"Rúguǒ" i "jiù"?','"Rúguǒ" and "jiù"?',['Samo prvi','Oba','Samo drugi','Nijedan'],1,
    '假设句：如+条件+就+结果。"如果"可省略。','Uslovne rečenice: rúguǒ+uslov+jiù+rezultat.','Conditional: if+condition+then+result.',10],
  [70,70,'📚','综合复习4','Pregled 4','Review 4',
    [w('复习','fù xí','Ponoviti'),w('应用','yìng yòng','Primena'),w('表达','biǎo dá','Izraz'),w('交流','jiāo liú','Komunikacija'),w('丰富','fēng fù','Bogat'),w('进步','jìn bù','Napredak')],
    'A: 学了这些复杂句子感觉如何？\nB: 能表达更多意思了！\nA: 现在交流丰富多了。\nB: 是的进步很大！','A: Složene rečenice?\nB: Mogu više izraziti!\nA: Ričnije komuniciraš.\nB: Da, veliki napredak!','A: Complex sentences?\nB: Can express more!\nA: Richer communication.\nB: Yes, big progress!',
    '复习：先然后最后(顺序)、因为所以(因果)、虽然但是(转折)、如果就(假设)。','Pregled: vremenski red, uzrok, kontrast, uslov.','Review: sequence, cause, contrast, condition.',
    '"所以"表什么？','Šta "suǒ yǐ"?','What "suǒ yǐ"?',['Ali','Zato','Ako','Iako'],1,
    '现在能用复杂句子表达观点！继续加油！','Sada možeš složenije izraze! Samo napred!','Can use complex sentences now! Keep going!',15],
  [71,71,'✈️','旅行','Putovanje','Travel',
    [w('旅行','lǚ xíng','Putovati'),w('行李','xíng li','Prtljag'),w('护照','hù zhào','Pasoš'),w('签证','qiān zhèng','Viza'),w('机票','jī piào','Avionska karta'),w('酒店','jiǔ diàn','Hotel')],
    'A: 你准备去旅行吗？\nB: 对要去中国。\nA: 签证办好了吗？\nB: 都办好了。','A: Planiraš putovanje?\nB: Da, u Kinu.\nA: Viza?\nB: Gotova.','A: Planning travel?\nB: Yes, to China.\nA: Visa?\nB: Ready.',
    '"准备"+动词=plan to。"办好了"=done/ready。"对"=yes(correct)。','"Zhǔnbèi"+glagol=planirati. "Bàn hǎo le"=gotovo.','"Zhǔnbèi"+verb=plan to. "Bàn hǎo le"=ready.',
    '"签证"是什么？','Šta "qiān zhèng"?','What "qiān zhèng"?',['Pasoš','Viza','Karta','Hotel'],1,
    '塞尔维亚公民去中国免签30天。中国去塞尔维亚也免签。','Srbija bez vize u Kinu 30 dana.','Serbia visa-free to China 30 days.',10],
  [72,72,'📋','计划安排','Planiranje','Planning',
    [w('计划','jì huà','Plan'),w('安排','ān pái','Raspored'),w('日程','rì chéng','Program'),w('参观','cān guān','Posetiti'),w('参加','cān jiā','Učestvovati'),w('体验','tǐ yàn','Iskustvo')],
    'A: 明天的计划是什么？\nB: 上午参观故宫下午逛街。\nA: 晚上呢？\nB: 参加火锅体验。','A: Plan za sutra?\nB: Jutro Zabranjeni grad, popodne šoping.\nA: Veče?\nB: Hot pot iskustvo.','A: Tomorrow\'s plan?\nB: Morning Forbidden City, afternoon shop.\nA: Evening?\nB: Hot pot experience.',
    '"上午/下午/晚上"+活动。"的"表所属。','Jutro/popodne/veče+aktivnost.','Morning/afternoon/evening+activity.',
    '"参观"的意思？','Šta "cān guān"?','What "cān guān"?',['Jesti','Posetiti','Kupiti','Spavati'],1,
    '故宫(紫禁城)是北京必游景点。中国历史五千年。','Zabranjeni grad obavezan u Pekingu.','Forbidden City must-visit in Beijing.',10],
  [73,73,'💡','建议推荐','Predlozi','Suggestions',
    [w('建议','jiàn yì','Predlog'),w('推荐','tuī jiàn','Preporuka'),w('应该','yīng gāi','Trebalo bi'),w('最好','zuì hǎo','Najbolje'),w('试试','shì shì','Probati'),w('不错','bú cuò','Nije loše')],
    'A: 我饿了有什么推荐？\nB: 你应该试试北京烤鸭。\nA: 哪家好吃？\nB: 全聚德不错。','A: Gladan. Preporuka?\nB: Probaj Peking patku.\nA: Gde?\nB: Quanjude nije loše.','A: Hungry. Recommend?\nB: Try Peking duck.\nA: Where?\nB: Quanjude is good.',
    '"应该"+动词=should。"试试"=try。"推荐"=recommendation。','"Yīnggāi"+glagol=trebalo bi. "Shìshi"=probaj.','"Yīnggāi"+verb=should. "Shìshi"=try.',
    '"推荐"的意思？','Šta "tuī jiàn"?','What "tuī jiàn"?',['Kritika','Preporuka','Porudžbina','Plaćanje'],1,
    '北京烤鸭是中国最著名的菜肴之一。全聚德创立于1864年。','Pekinška patka najpoznatije jelo. Quanjude osnovan 1864.','Peking duck most famous dish. Quanjude est.1864.',10],
  [74,74,'🌱','环保自然','Ekologija','Environment',
    [w('环境','huán jìng','Životna sredina'),w('保护','bǎo hù','Zaštita'),w('污染','wū rǎn','Zagađenje'),w('垃圾分类','lā jī fēn lèi','Sortiranje otpada'),w('回收','huí shōu','Reciklaža'),w('绿色','lǜ sè','Zeleno')],
    'A: 你们那儿环保好吗？\nB: 现在垃圾分类很严格。\nA: 大家都参与吗？\nB: 大多数人都做。','A: Ekologija kod vas?\nB: Sortiranje otpada strogo.\nA: Svi učestvuju?\nB: Većina.','A: Environment there?\nB: Waste sorting strict.\nA: Everyone participates?\nB: Most people.',
    '"很+形容词"=very。"大多数"=most/majority。"参与"=participate。','"Hěn"+pridev=veoma. "Dà duō shù"=većina.','"Hěn"+adj=very. "Dà duō shù"=majority.',
    '"环保"是什么意思？','Šta "huán bǎo"?','What "huán bǎo"?',['Priroda','Ekologija','Hemija','Biologija'],1,
    '上海2019年开始垃圾分类。中国正在大力治理环境污染。','Šangaj 2019 uveo sortiranje otpada. Kina se bori protiv zagađenja.','Shanghai 2019 waste sorting. China fighting pollution.',10],
  [75,75,'💪','健康生活','Zdrav život','Healthy Life',
    [w('健康','jiàn kāng','Zdravlje'),w('运动','yùn dòng','Vežbanje'),w('跑步','pǎo bù','Trčanje'),w('瑜伽','yú jiā','Joga'),w('减肥','jiǎn féi','Mršavljenje'),w('睡眠','shuì mián','San')],
    'A: 你平时运动吗？\nB: 每天跑步半小时。\nA: 难怪你这么健康。\nB: 你也应该试试！','A: Vežbaš?\nB: Trčim 30 min dnevno.\nA: Zato si zdrav.\nB: I ti probaj!','A: Exercise?\nB: Run 30 min daily.\nA: That\'s why healthy.\nB: You try too!',
    '"平时"=usually。"每天"=every day。"难怪"=no wonder。"半小时"=half hour。','"Píngshí"=obično. "Měi tiān"=svaki dan. "Bàn xiǎoshí"=pola sata.','"Píngshí"=usually. "Bàn xiǎoshí"=half hour.',
    '"健康"副词？','Prilog "jiàn kāng"?','Adverb of "jiàn kāng"?',['健健康','健康地','很健康','健康的'],2,
    '中国老年人公园晨练(太极、广场舞)。年轻人去健身房。','Stariji vežbaju u parku (taici). Mlađi u teretani.','Elderly exercise in parks (tai chi). Youth gym.',10],
  [76,76,'⚽','体育运动','Sport','Sports',
    [w('足球','zú qiú','Fudbal'),w('篮球','lán qiú','Košarka'),w('乒乓球','pīng pāng qiú','Stoni tenis'),w('游泳','yóu yǒng','Plivanje'),w('比赛','bǐ sài','Utakmica'),w('冠军','guàn jūn','Šampion')],
    'A: 你喜欢什么运动？\nB: 喜欢篮球和乒乓球。\nA: 看比赛吗？\nB: 周末常看NBA。','A: Koji sport?\nB: Košarka, stoni tenis.\nA: Gledaš utakmice?\nB: Vikendom NBA.','A: What sport?\nB: Basketball, table tennis.\nA: Watch games?\nB: Weekends NBA.',
    '"打"+球类运动。"看比赛"=watch game。','"Dǎ"+loptu. "Kàn bǐsài"=gledati utakmicu.','"Dǎ"+ball game. "Kàn bǐsài"=watch game.',
    '"乒乓球"是中国什么？','Šta je ping pong u Kini?','What is ping pong in China?',['Igra','Nacionalni sport','Hobi','Posao'],1,
    '乒乓球是中国国球。中国队在奥运会几乎包揽金牌。塞尔维亚篮球世界强队。','Stoni tenis nacionalni sport Kine. Srbija jaka u košarci.','Table tennis national sport. Serbia strong in basketball.',10],
  [77,77,'🎵','音乐艺术','Muzika i umetnost','Music & Art',
    [w('音乐','yīn yuè','Muzika'),w('唱歌','chàng gē','Pevanje'),w('吉他','jí tā','Gitara'),w('钢琴','gāng qín','Klavir'),w('画画','huà huà','Slikanje'),w('观众','guān zhòng','Publika')],
    'A: 你会乐器吗？\nB: 会弹吉他。\nA: 学了多久了？\nB: 学了三年了。','A: Svirate instrument?\nB: Gitaru.\nA: Koliko dugo?\nB: Tri godine.','A: Play instrument?\nB: Guitar.\nA: How long?\nB: Three years.',
    '"会"+技能=can(skill)。"学了"+时间+"了"=have been doing for。','"Huì"+veština=umeti. "Xué le"+vreme+"le"=učim već.','"Huì"+skill=can. "Xué le"+time+"le"=have been learning.',
    '"观众"是什么意思？','Šta "guān zhòng"?','What "guān zhòng"?',['Pevači','Publika','Muzičari','Plesači'],1,
    '中国古典音乐：古筝、二胡、琵琶。塞尔维亚传统音乐：gusle、kolo dance。','Kineska klasična muzika: guzheng, erhu. Srpska: gusle, kolo.','Chinese classical: guzheng, erhu. Serbian: gusle, kolo.',10],
  [78,78,'🎬','电影电视','Film i TV','Movies & TV',
    [w('电影','diàn yǐng','Film'),w('电视','diàn shì','TV'),w('导演','dǎo yǎn','Reditelj'),w('演员','yǎn yuán','Glumac'),w('剧情','jù qíng','Radnja'),w('搞笑','gǎo xiào','Smešan')],
    'A: 最近有什么好电影？\nB: 这部新片很搞笑。\nA: 谁导演的？\nB: 一个年轻导演。','A: Dobar film u poslednje vreme?\nB: Novi je smešan.\nA: Ko je reditelj?\nB: Mladi reditelj.','A: Any good movies lately?\nB: New one is funny.\nA: Who directed?\nB: A young director.',
    '"最近"=recently。"好"=good。"新片"=new movie。"谁+动词"=who+verb。','"Zuì jìn"=u poslednje vreme. "Shuí"=ko.','"Zuì jìn"=recently. "Shuí"=who.',
    '"导演"做什么？','Šta radi "dǎo yǎn"?','What does "dǎo yǎn" do?',['Glumi','Režira','Pevati','Piše'],1,
    '中国电影：卧虎藏龙、霸王别姬。中国票房市场全球第二。','Kineski filmovi: Crouching Tiger, Farewell My Concubine. 2. najveće tržište.','Chinese films: Crouching Tiger. 2nd largest market.',10],
  [79,79,'📚','读书学习','Čitanje i učenje','Reading & Learning',
    [w('看书','kàn shū','Čitati'),w('图书馆','tú shū guǎn','Biblioteka'),w('小说','xiǎo shuō','Roman'),w('教材','jiào cái','Udžbenik'),w('笔记','bǐ jì','Beleške'),w('考试','kǎo shì','Ispit')],
    'A: 你平时喜欢看什么书？\nB: 喜欢看小说。\nA: 汉语教材呢？\nB: 也看为了准备HSK考试。','A: Šta čitaš?\nB: Roman.\nA: Udžbenike?\nB: Da, za HSK ispit.','A: What do you read?\nB: Novels.\nA: Textbooks?\nB: Yes, for HSK exam.',
    '"为了"+目的=in order to。"准备"+考试=prepare for exam。','"Wèi le"+cilj=da bi. "Zhǔnbèi"+ispit=spremati.','"Wèi le"+purpose=in order to. "Zhǔnbèi"+exam=prepare.',
    '"图书馆"是什么地方？','Šta je "tú shū guǎn"?','What "tú shū guǎn"?',['Prodavnica','Biblioteka','Restoran','Muzej'],1,
    'HSK(汉语水平考试)有6级。塞尔维亚有多个HSK考点。','HSK ispit za kineski ima 6 nivoa. Ispitni centri u Srbiji.','HSK Chinese test has 6 levels. Test centers in Serbia.',10],
  [80,80,'📚','综合复习5','Pregled 5','Review 5',
    [w('复习','fù xí','Ponoviti'),w('总结','zǒng jié','Sumiranje'),w('词汇','cí huì','Rečnik'),w('句型','jù xíng','Obrasci'),w('提升','tí shēng','Unaprediti'),w('目标','mù biāo','Cilj')],
    'A: 这阶段学了什么？\nB: 社会话题、旅行、建议等。\nA: 词汇量提升了吗？\nB: 是的目标达到了！','A: Naučio u ovoj fazi?\nB: Društvene teme, putovanja.\nA: Rečnik?\nB: Da, cilj ostvaren!','A: Learned this phase?\nB: Social topics, travel.\nA: Vocabulary?\nB: Yes, goal achieved!',
    '复习：租房求职、社交网络、时间顺序、因果关系、假设条件、建议推荐。','Pregled: iznajmljivanje, posao, društvene mreže, itd.','Review: renting, job, social media, etc.',
    '"词汇"的意思？','Šta "cí huì"?','What "cí huì"?',['Gramatika','Rečnik','Izgovor','Pisanje'],1,
    '第三阶段完成！现在能用汉语讨论复杂话题了。','Faza 3 gotova! Možeš o složenim temama.','Phase 3 done! Can discuss complex topics.',15],
  [81,81,'🏙️','描述城市','Opis grada','Describing City',
    [w('城市','chéng shì','Grad'),w('热闹','rè nào','Živahno'),w('安静','ān jìng','Tiho'),w('现代化','xiàn dài huà','Moderan'),w('古老','gǔ lǎo','Star'),w('繁华','fán huá','Bujno')],
    'A: 北京是什么样的城市？\nB: 又古老又现代化。\nA: 热闹吗？\nB: 非常热闹。','A: Kakav je Peking?\nB: I star i moderan.\nA: Živahno?\nB: Veoma.','A: What is Beijing like?\nB: Both old and modern.\nA: Lively?\nB: Very.',
    '"又...又..."=both...and...。','"Yòu...yòu..."=i...i...。','Yòu...yòu..."=both...and...',
    '"热闹"的反义词？','Antonim "rè nào"?','Antonym of "rè nào"?',['安静','繁华','快乐','拥挤'],0,
    '北京有三千多年历史。故宫长城天坛。塞尔维亚首都贝尔格莱德也有悠久历史。','Peking ima 3000+ godina istorije. Beograd takođe istorijski.','Beijing 3000+ years. Belgrade also historic.',10],
  [82,82,'👤','人物外貌','Izgled osobe','Appearance',
    [w('高','gāo','Visok'),w('矮','ǎi','Nizak'),w('胖','pàng','Debeo'),w('瘦','shòu','Mršav'),w('帅','shuài','Zgodan'),w('美','měi','Lepa')],
    'A: 你男朋友长什么样？\nB: 很高很帅。\nA: 头发什么颜色？\nB: 黑色短发。','A: Kako izgleda tvoj dečko?\nB: Visok, zgodan.\nA: Boja kose?\nB: Crna, kratka.','A: What does your boyfriend look like?\nB: Tall, handsome.\nA: Hair color?\nB: Black, short.',
    '描述外貌：身高+体型+长相。','"Kàn qǐlái"=looks like。','Opis: visina+gradnja+izgled.',
    '"帅"形容谁？','"Shuài" za koga?','"Shuài" for whom?',['Žene','Muškarce','Decu','Starce'],1,
    '中国人描述外貌先说整体后说细节。避免直接评论体重(不礼貌)。','Kinezi opisuju celinu pa detalje. Izbegavaj komentarisanje težine.','Chinese describe whole then details. Avoid weight comments.',10],
  [83,83,'🧑‍🤝‍🧑','人物性格','Karakter','Personality',
    [w('性格','xìng gé','Karakter'),w('开朗','kāi lǎng','Vedar'),w('幽默','yōu mò','Humoran'),w('善良','shàn liáng','Dobar'),w('聪明','cōng míng','Pametan'),w('努力','nǔ lì','Vredan')],
    'A: 塞尔维亚人性格怎么样？\nB: 很开朗热情。\nA: 中国人呢？\nB: 比较含蓄但很善良。','A: Kakvi su Srbi?\nB: Vedri, gostoljubivi.\nA: Kinezi?\nB: Suzdržani ali dobri.','A: What are Serbians like?\nB: Cheerful, hospitable.\nA: Chinese?\nB: Reserved but kind.',
    '"比较"+形容词表示moderately。"很"+形容词表示very。','"Bǐjiào"+pridev=umereno. "Hěn"+pridev=veoma.','"Bǐjiào"+adj=moderately. "Hěn"+adj=very.',
    '"开朗"是褒义还是贬义？','"Kāi lǎng" pozitivno ili negativno?','"Kāi lǎng" positive or negative?',['Pozitivno','Negativno','Neutralno','Zavisi'],0,
    '塞尔维亚人直接热情。中国人相对内敛。跨文化理解很重要。','Srbi direktni, topli. Kinezi suzdržani. Međukulturno razumevanje važno.','Serbs direct, warm. Chinese reserved. Cross-cultural understanding important.',10],
  [84,84,'🗣️','表达意见','Izražavanje mišljenja','Expressing Opinions',
    [w('觉得','jué de','Misliti'),w('认为','rèn wéi','Smatrati'),w('意见','yì jiàn','Mišljenje'),w('同意','tóng yì','Složiti se'),w('反对','fǎn duì','Protiviti'),w('观点','guān diǎn','Stav')],
    'A: 你觉得这部电影怎么样？\nB: 我觉得很好看。\nA: 你同意吗？\nB: 完全同意！','A: Šta misliš o filmu?\nB: Mislim da je dobar.\nA: Slažeš se?\nB: Potpuno!','A: What do you think of this movie?\nB: I think it\'s good.\nA: Agree?\nB: Totally!',
    '"觉得/认为"=think/feel。"完全同意"=totally agree。"反对"=oppose。','"Juéde/rènwéi"=misliti. "Tóngyì"=složiti se.','"Juéde/rènwéi"=think. "Tóngyì"=agree.',
    '"同意"的反义词？','Antonim "tóng yì"?','Antonym "tóng yì"?',['反对','支持','喜欢','明白'],0,
    '中国人表达意见较委婉。\"我觉得\"比\"我认为\"更温和。','Kinezi izražavaju mišljenje blago. "Juéde" je mekše od "rènwéi".','Chinese express opinions gently. "Juéde" softer.',10],
  [85,85,'💬','争论解释','Rasprava','Arguing & Explaining',
    [w('争论','zhēng lùn','Raspravljati'),w('解释','jiě shì','Objasniti'),w('明白','míng bai','Razumeti'),w('误会','wù huì','Nesporazum'),w('道理','dào lǐ','Logika'),w('证明','zhèng míng','Dokazati')],
    'A: 你们在争论什么？\nB: 他误会了我的意思。\nA: 你解释清楚了吗？\nB: 解释了现在他明白了。','A: O čemu raspravljate?\nB: Pogrešno me razumeo.\nA: Objasnio si?\nB: Da, sad razume.','A: What are you arguing about?\nB: He misunderstood me.\nA: Did you explain?\nB: Yes, now he understands.',
    '"解释"+给+人=explain to。"误会"=misunderstanding。"清楚"=clear。','"Jiěshì"+dati+osobi=objasniti. "Wùhuì"=nesporazum.','"Jiěshì"+give+person=explain. "Wùhuì"=misunderstanding.',
    '"误会"的意思？','Šta "wù huì"?','What "wù huì"?',['Razumeti','Nesporazum','Složiti','Objasniti'],1,
    '中国人争论时保持礼貌，避免直接说\"你错了\"。用\"可能我还没说清楚\"。','Kinezi ostaju učtivi u raspravi. Izbegavaju "grešiš".','Chinese stay polite in arguments.',10],
  [86,86,'🤗','安慰鼓励','Uteha i ohrabrenje','Comfort & Encouragement',
    [w('安慰','ān wèi','Tešiti'),w('鼓励','gǔ lì','Ohrabriti'),w('别担心','bié dān xīn','Ne brini'),w('没关系','méi guān xì','Nema veze'),w('加油','jiā yóu','Samo napred'),w('你可以的','nǐ kě yǐ de','Možeš ti to')],
    'A: 我考试没考好很难过。\nB: 别担心下次加油！\nA: 但是我很努力了。\nB: 没关系你可以的！','A: Ispit loše prošao.\nB: Ne brini, sledeći put!\nA: Al\' sam se trudio.\nB: Nema veze, možeš ti to!','A: Failed exam, sad.\nB: Don\'t worry, next time!\nA: But I tried hard.\nB: It\'s OK, you can do it!',
    '"没考好"=didn\'t do well。"下次"=next time。"你可以的"=you can do it。','"Méi kǎo hǎo"=loše prošao. "Xià cì"=sledeći put.','"Méi kǎo hǎo"=did poorly. "Xià cì"=next time.',
    '"加油"用于什么场合？','Kada se kaže "jiā yóu"?','When to say "jiā yóu"?',['Zbogom','Ohrabrenje','Izvini','Hvala'],1,
    '中国人互相鼓励说"加油"。考试前朋友互道"加油"。塞尔维亚人说"samo napred"。','Kinezi kažu "jiā yóu" za ohrabrenje. Srbi "samo napred".','Chinese say "jiā yóu". Serbs "samo napred".',10],
  [87,87,'🎊','祝贺祝福','Čestitke','Congratulations',
    [w('祝贺','zhù hè','Čestitati'),w('恭喜','gōng xǐ','Čestitam'),w('祝福','zhù fú','Blagoslov'),w('好运','hǎo yùn','Sreća'),w('成功','chéng gōng','Uspeh'),w('幸福','xìng fú','Sreća')],
    'A: 我找到工作了！\nB: 恭喜恭喜！\nA: 谢谢祝福我吧。\nB: 祝你工作顺利！','A: Našao sam posao!\nB: Čestitam!\nA: Hvala, blagoslovi me.\nB: Srećno na poslu!','A: Found a job!\nB: Congratulations!\nA: Thanks, wish me luck.\nB: Wish you success at work!',
    '"恭喜恭喜"常在节日和成功时说。"祝你"+祝福语=wish you+sth。','"Gōngxǐ gōngxǐ"=čestitam. "Zhù nǐ"+blagoslov=želim ti.','"Gōngxǐ gōngxǐ"=congrats. "Zhù nǐ"+wish.',
    '"祝福"的意思？','Šta "zhù fú"?','What "zhù fú"?',['Pomoć','Blagoslov/želja','Zahvala','Pozdrav'],1,
    '中国春节说"恭喜发财"(wish you wealth)。生日说"生日快乐"。结婚说"百年好合"。','"Gōngxǐ fācái" za NG. "Shēngrì kuàilè" za rođendan.','"Gōngxǐ fācái" for NY. "Shēngrì kuàilè" for birthday.',10],
  [88,88,'💍','谈婚论嫁','Brak i veridba','Marriage',
    [w('结婚','jié hūn','Venčati'),w('订婚','dìng hūn','Veridba'),w('婚礼','hūn lǐ','Venčanje'),w('婚纱','hūn shā','Venčanica'),w('戒指','jiè zhi','Prsten'),w('蜜月','mì yuè','Medeni mesec')],
    'A: 你们打算什么时候结婚？\nB: 明年春天。\nA: 中式婚礼还是西式？\nB: 想要中西结合。','A: Kada planirate venčanje?\nB: Sledeće proleće.\nA: Kineski ili zapadni stil?\nB: Kombinacija.','A: When plan to marry?\nB: Next spring.\nA: Chinese or Western style?\nB: Combination.',
    '"打算"+动词=plan to。"还是"用于选择问句。','"Háishì"=or(in questions)。','"Dǎsuàn"+verb=plan to. "Háishì"=or.',
    '"蜜月"是什么？','Šta "mì yuè"?','What "mì yuè"?',['Svadba','Medeni mesec','Prsten','Poklon'],1,
    '中国婚俗：彩礼、红色婚纱(传统)、敬茶。塞尔维亚婚俗：kum(教父)、slavlje。','Kineske svadbe: crveno, čaj. Srpske: kum, slavlje.','Chinese weddings: red, tea ceremony. Serbian: kum, celebration.',10],
  [89,89,'🌍','中塞文化对比','Kinesko-srpsko poređenje','China-Serbia Culture',
    [w('文化','wén huà','Kultura'),w('传统','chuán tǒng','Tradicija'),w('习惯','xí guàn','Navika'),w('不同','bù tóng','Različito'),w('相同','xiāng tóng','Isto'),w('有趣','yǒu qù','Zanimljivo')],
    'A: 中塞文化有什么不同？\nB: 中国人比较含蓄塞尔维亚人很直接。\nA: 相同点呢？\nB: 都很热情好客。','A: Razlike Kina-Srbija?\nB: Kinezi suzdržani, Srbi direktni.\nA: Sličnosti?\nB: Oba gostoljubivi.','A: Differences China-Serbia?\nB: Chinese reserved, Serbs direct.\nA: Similarities?\nB: Both hospitable.',
    '"有什么不同"=what differences。"比较"=relatively。"很+形"=very+adj。','"Yǒu shénme bùtóng"=koje razlike. "Bǐjiào"=relativno.','"Yǒu shénme bùtóng"=what differences.',
    '"好客"的意思？','Šta "hào kè"?','What "hào kè"?',['Gostoljubiv','Prijateljski','Učtiv','Topao'],0,
    '中塞都是热情好客的民族。中国茶文化VS塞尔维亚咖啡文化。两国都重视家庭和友谊。','Kina i Srbija gostoljubive. Čaj vs kafa. Obe cene porodicu.','China and Serbia both hospitable. Tea vs coffee culture.',10],
  [90,90,'📚','综合复习6','Pregled 6','Review 6',
    [w('复习','fù xí','Ponoviti'),w('努力','nǔ lì','Trud'),w('坚持','jiān chí','Istrajati'),w('进步','jìn bù','Napredak'),w('目标','mù biāo','Cilj'),w('实现','shí xiàn','Ostvariti')],
    'A: 第三阶段学完了！\nB: 是的进步很大！\nA: 继续努力坚持。\nB: 目标是实现流利交流。','A: Faza 3 gotova!\nB: Da, veliki napredak!\nA: Nastavi istrajno.\nB: Cilj: tečna komunikacija.','A: Phase 3 done!\nB: Yes, big progress!\nA: Keep working hard.\nB: Goal: fluent communication.',
    '复习：描述城市、人物外貌性格、表达意见、安慰鼓励、祝贺祝福、文化对比。','Pregled: opis grada, izgled, karakter, mišljenje, čestitke, kultura.','Review: city description, appearance, opinions, congrats, culture.',
    '"坚持"的意思？','Šta "jiān chí"?','What "jiān chí"?',['Početi','Istrajati','Završiti','Planirati'],1,
    '第三阶段完成！现在能用汉语做深度交流了。准备进入情感对话阶段！','Faza 3 gotova! Spremi se za emocionalne dijaloge!','Phase 3 done! Ready for emotional dialogues!',15],
];

module.exports = { p3data };
