// Phase 2-6 lesson data (compact format)
// Each: [id,day,icon,zh_topic,sr_topic,en_topic,words[],zh_d,sr_d,en_d,zh_g,sr_g,en_g,zh_q,sr_q,en_q,opts[],correct,zh_c,sr_c,en_c,pts]
const w = (zh,py,sr)=>{return {zh,py,sr}};

// Helpers for building the data with string helper
function T(zh, sr, en) { return { zh, sr, en }; }

const p2data = [
  // Phase 2: Daily Life (31-60)
  [31,31,'🍽️','在餐厅（一）','Restoran(1)','At Restaurant(1)',
    [w('菜单','cài dān','Meni'),w('点菜','diǎn cài','Naručiti'),w('服务员','fú wù yuán','Konobar'),w('筷子','kuài zi','Štapići'),w('碗','wǎn','Činija'),w('盘子','pán zi','Tanji')],
    'A: 服务员请给我菜单。\nB: 好的，这是菜单。\nA: 我想点这个菜。\nB: 请稍等。','A: Konobar, meni.\nB: Izvolite.\nA: Želim ovo.\nB: Sačekajte.','A: Waiter, menu.\nB: Here.\nA: I want this.\nB: Please wait.',
    '"请"表礼貌。"给"+我+物品。','"Qǐng"=molim(učtivo).','"Qǐng"=please(polite).',
    '"点菜"的意思？','Šta "diǎn cài"?','What "diǎn cài"?',['Platiti','Naručiti','Jesti','Kuhati'],1,
    '勿把筷子插饭里(像上香)。AA制流行。','Štapiće ne u pirinač.','Don\'t stick chopsticks in rice.',10],
  [32,32,'🍽️','在餐厅（二）','Restoran(2)','At Restaurant(2)',
    [w('好吃','hǎo chī','Ukusno'),w('辣','là','Ljuto'),w('咸','xián','Sleno'),w('甜','tián','Slatko'),w('酸','suān','Kiselo'),w('买单','mǎi dān','Račun')],
    'A: 这个菜怎么样？\nB: 很好吃但是很辣。\nA: 你能吃辣吗？\nB: 一点点。服务员买单！','A: Kako jelo?\nB: Ukusno ali ljuto.\nA: Možeš ljuto?\nB: Malo. Račun!','A: How dish?\nB: Tasty but spicy.\nA: Handle spicy?\nB: A little. Check!',
    '"但是"表转折。"能"表能力。','"Dànshì"=ali. "Néng"=moći.','"Dànshì"=but. "Néng"=can.',
    '"买单"的意思？','Šta "mǎi dān"?','What "mǎi dān"?',['Kupiti','Naručiti','Tražiti račun','Jesti'],2,
    '"买单"也可说"结账"。请客是友谊表现。','"Mǎi dān" ili "jié zhàng".','"Mǎi dān" or "jié zhàng".',10],
  [33,33,'🛍️','购物（一）','Kupovina(1)','Shopping(1)',
    [w('多少钱','duō shao qián','Koliko'),w('贵','guì','Skupo'),w('便宜','pián yi','Jeftino'),w('买','mǎi','Kupiti'),w('卖','mài','Prodati'),w('打折','dǎ zhé','Popust')],
    'A: 这个多少钱？\nB: 一百块。\nA: 太贵了！能便宜吗？\nB: 打八折。','A: Koliko?\nB: 100.\nA: Preskupo! Jeftinije?\nB: 20% popusta.','A: How much?\nB: 100.\nA: Too expensive! Cheaper?\nB: 20% off.',
    '"多少钱"问价。"太...了"表过度。','"Duōshao qián"=koliko. "Tài...le"=previše.','"Duōshao qián"=how much.',
    '"打折"的意思？','Šta "dǎ zhé"?','What "dǎ zhé"?',['Poklon','Popust','Skupo','Jeftino'],1,
    '可讨价还价(市场)。商场固定价。"块"=元口语。','Cenkanje na pijacama.','Bargaining at markets.',10],
  [34,34,'🛍️','购物（二）','Kupovina(2)','Shopping(2)',
    [w('试穿','shì chuān','Probati'),w('大号','dà hào','Veliko'),w('小号','xiǎo hào','Malo'),w('颜色','yán sè','Boja'),w('合适','hé shì','Odgovara'),w('退换','tuì huàn','Vratiti')],
    'A: 这件可以试穿吗？\nB: 可以试衣间那边。\nA: 太大了有小号吗？\nB: 有给你。','A: Mogu probati?\nB: Da, kabina tamo.\nA: Preveliko. Manje?\nB: Izvolite.','A: Can I try?\nB: Yes, fitting room.\nA: Too big. Smaller?\nB: Here.',
    '"可以"表允许。"有...吗？"询问存在。','"Kěyǐ"=dozvola.','"Kěyǐ"=allowed.',
    '"试穿"的意思？','Šta "shì chuān"?','What "shì chuān"?',['Kupiti','Probati odeću','Pogledati','Platiti'],1,
    '网购：淘宝京东拼多多。双十一最大购物节。','Taobao, JD. 11.11 najveći.','Taobao, JD. 11.11 biggest.',10],
  [35,35,'🗺️','问路（一）','Traženje puta(1)','Asking Directions(1)',
    [w('请问','qǐng wèn','Izvinite'),w('怎么走','zěn me zǒu','Kako se ide'),w('左转','zuǒ zhuǎn','Levo'),w('右转','yòu zhuǎn','Desno'),w('一直走','yī zhí zǒu','Pravo'),w('路口','lù kǒu','Raskrsnica')],
    'A: 请问去火车站怎么走？\nB: 一直走第二个路口左转。\nA: 远吗？\nB: 不远走路十分钟。','A: Izvinite do stanice?\nB: Pravo, drugi ćošak levo.\nA: Daleko?\nB: Nije, 10 min.','A: Excuse me to station?\nB: Straight, 2nd left.\nA: Far?\nB: No, 10 min walk.',
    '"请问"礼貌提问。"怎么走"问路。','"Qǐng wèn"=učtivo pitanje.','"Qǐng wèn"=polite question.',
    '"请问"在问路表示？','Šta "qǐng wèn"?','What "qǐng wèn"?',['Hvala','Izvinite(pitam)','Zbogom','Dobro'],1,
    '中国人乐于助人。用手机地图导航。','Kinezi rado pomažu. Koristite mapu.','Chinese helpful. Use map.',10],
  [36,36,'🗺️','问路（二）','Traženje puta(2)','Asking Directions(2)',
    [w('附近','fù jìn','U blizini'),w('红绿灯','hóng lǜ dēng','Semafor'),w('过','guò','Preći'),w('第一个','dì yī gè','Prvi'),w('地铁站','dì tiě zhàn','Metro'),w('公交车站','gōng jiāo chē zhàn','Autobuska')],
    'A: 附近有地铁站吗？\nB: 有过两个红绿灯就到了。\nA: 左边还是右边？\nB: 右边。','A: Ima li metro?\nB: Posle 2 semafora.\nA: Levo ili desno?\nB: Desno.','A: Metro nearby?\nB: After 2 lights.\nA: Left or right?\nB: Right.',
    '"有...吗？"询问存在。"过+数字+红绿灯"。','"Yǒu...ma?"=ima li?','"Yǒu...ma?"=is there?',
    '"红绿灯"是什么？','Šta "hóng lǜ dēng"?','What "hóng lǜ dēng"?',['Znak','Semafor','Ulica','Most'],1,
    '中国大城市地铁发达。北京地铁世界最长。','Kineski metro razvijen.','Chinese metro developed.',10],
  [37,37,'🚗','交通工具','Prevoz','Transportation',
    [w('公共汽车','gōng gòng qì chē','Autobus'),w('地铁','dì tiě','Metro'),w('出租车','chū zū chē','Taksi'),w('自行车','zì xíng chē','Bicikl'),w('火车','huǒ chē','Voz'),w('飞机','fēi jī','Avion'),w('走路','zǒu lù','Peške')],
    'A: 你怎么去上班？\nB: 坐地铁。\nA: 挤吗？\nB: 早上很挤。','A: Kako na posao?\nB: Metroom.\nA: Puno?\nB: Ujutro veoma.','A: How to work?\nB: By metro.\nA: Crowded?\nB: Very morning.',
    '"坐/骑/开"+交通工具。"怎么去"问交通方式。','"Zuò/qí/kāi"+prevoz.','"Zuò/qí/kāi"+transport.',
    '"骑自行车"中"骑"表示？','Šta "qí"?','What "qí"?',['Voziti auto','Jašiti bicikl','Popraviti','Kupiti'],1,
    '"自行车王国"。高铁网络世界最大。','"Carstvo bicikala". Brzi vozovi.','"Bicycle kingdom". HSR largest.',10],
  [38,38,'🎫','买票和预约','Karte i rezervacije','Tickets & Reservations',
    [w('票','piào','Karta'),w('预订','yù dìng','Rezervisati'),w('座位','zuò wèi','Sedište'),w('靠窗','kào chuāng','Do prozora'),w('价格','jià gé','Cena'),w('退票','tuì piào','Povrat')],
    'A: 我要买两张去北京的票。\nB: 要靠窗的座位吗？\nA: 是的多少钱？\nB: 一共五百。','A: Dve karte za Peking.\nB: Do prozora?\nA: Da, koliko?\nB: 500.','A: Two tickets to Beijing.\nB: Window seat?\nA: Yes, how much?\nB: 500.',
    '"要"表想要。"一共"表总计。','"Yào"=želeti. "Yígòng"=ukupno.','"Yào"=want. "Yígòng"=total.',
    '"预订"的意思？','Šta "yù dìng"?','What "yù dìng"?',['Kupiti','Rezervisati','Otkazati','Platiti'],1,
    '高铁非常方便。春节票紧张需提前抢。','Brzi vozovi odlični. Karte unapred.','HSR excellent. Book ahead.',10],
  [39,39,'🏨','在酒店','U hotelu','At Hotel',
    [w('房间','fáng jiān','Soba'),w('入住','rù zhù','Prijava'),w('退房','tuì fáng','Odjava'),w('钥匙卡','yào shi kǎ','Kartica'),w('早餐','zǎo cān','Doručak'),w('WiFi密码','wifi mì mǎ','WiFi šifra')],
    'A: 你好我预订了房间。\nB: 请给我护照。\nA: 早餐几点开始？\nB: 七点到十点。','A: Imam rezervaciju.\nB: Pasoš.\nA: Doručak?\nB: 7-10.','A: I have reservation.\nB: Passport.\nA: Breakfast?\nB: 7-10.',
    '"从...到..."表范围。"给+我"递东西。','"Cóng...dào..."=od...do.','"Cóng...dào..."=from...to.',
    '"入住"的意思？','Šta "rù zhù"?','What "rù zhù"?',['Napuštati','Prijava u hotel','Platiti','Rezervisati'],1,
    '酒店需护照登记。WiFi需手机验证。','Hotel traži pasoš. WiFi verifikacija.','Hotel needs passport.',10],
  [40,40,'📚','综合复习2','Pregled 2','Review 2',
    [w('总结','zǒng jié','Sumirati'),w('掌握','zhǎng wò','Ovladati'),w('运用','yùn yòng','Primeniti'),w('流利','liú lì','Tečno'),w('表达','biǎo dá','Izraziti'),w('沟通','gōu tōng','Komunikacija')],
    'A: 学了这么多觉得怎么样？\nB: 进步很大！\nA: 可以自己去点菜了吗？\nB: 可以了！','A: Pošto si naučio?\nB: Mnogo napredak!\nA: Možeš naručiti?\nB: Mogu!','A: After learning?\nB: Huge progress!\nA: Can order?\nB: Yes!',
    '复习："可以""但是""从...到...""多少钱""怎么走"。','Ponavljanje: kěyǐ, dànshì, cóng...dào...','Review: can, but, from...to, price, directions.',
    '"沟通"的意思？','Šta "gōu tōng"?','What "gōu tōng"?',['Govoriti','Komunicirati','Pisati','Čitati'],1,
    '已掌握日常交流！实践是最好的学习。','Već vladaš osnovama! Praksa je najbolja.','Mastered basics! Practice is best.',15],
  [41,41,'📞','电话沟通','Telefon','Phone Calls',
    [w('喂','wéi','Halo'),w('打电话','dǎ diàn huà','Pozvati'),w('接','jiē','Primiti'),w('留言','liú yán','Poruka'),w('回电话','huí diàn huà','Povratiti'),w('信号','xìn hào','Signal')],
    'A: 喂请问是王老师吗？\nB: 是您哪位？\nA: 我是安娜想预约明天的课。\nB: 好的明天下午两点。','A: Halo, profesor Vang?\nB: Da, ko?\nA: Ana, želim čas sutra.\nB: Sutra 14h.','A: Hello, Teacher Wang?\nB: Yes, who?\nA: Anna, want lesson tomorrow.\nB: Tomorrow 2PM.',
    '电话用语："喂""我是...""您哪位？"','Telefonski izrazi: "wéi".','Phone: "wéi", "wǒ shì...".',
    '打电话时说"喂"是什么意思？','"Wéi" na telefonu?','"Wéi" on phone?',['Zdravo','Halo','Doviđenja','Čekaj'],1,
    '中国接电话先说"喂"。工作场合先报单位。','Javljanje sa "wéi".','Answer with "wéi".',10],
  [42,42,'📅','约时间见面','Sastanak','Making Appointments',
    [w('见面','jiàn miàn','Sastati'),w('方便','fāng biàn','Zgodno'),w('时间','shí jiān','Vreme'),w('迟到','chí dào','Zakasniti'),w('提前','tí qián','Unapred'),w('取消','qǔ xiāo','Otkazati')],
    'A: 我们什么时候见面？\nB: 你什么时候方便？\nA: 明天下午三点行吗？\nB: 行到时候见！','A: Kada da se nađemo?\nB: Kad ti odgovara?\nA: Sutra 15h, važi?\nB: Važi!','A: When meet?\nB: When convenient?\nA: Tomorrow 3PM, OK?\nB: OK see you!',
    '"什么时候"问时间。"行吗？"征求意见。','"Shénme shíhou"=kada. "Xíng ma?"=u redu?','"Shénme shíhou"=when. "Xíng ma?"=OK?',
    '"迟到"的反义词？','Antonim "chí dào"?','Antonym "chí dào"?',['早到','取消','见面','等待'],0,
    '中国人越来越守时。社交"迟到10分"正常。','Tačnost sve važnija.','Punctuality increasingly important.',10],
  [43,43,'🏥','看病就医','Doktor','Seeing Doctor',
    [w('医院','yī yuàn','Bolnica'),w('生病','shēng bìng','Bolestan'),w('发烧','fā shāo','Temperatura'),w('头痛','tóu tòng','Glavobolja'),w('咳嗽','ké sou','Kašalj'),w('药','yào','Lek')],
    'A: 你哪里不舒服？\nB: 我头痛还发烧。\nA: 多久了？\nB: 两天了。\nA: 我给你开药。','A: Šta boli?\nB: Glava, temperatura.\nA: Koliko dugo?\nB: 2 dana.\nA: Prepisujem lekove.','A: What hurts?\nB: Head, fever.\nA: How long?\nB: 2 days.\nA: Prescribe meds.',
    '"哪里不舒服"问病状。"多久了"问持续。','"Nǎlǐ bù shūfu"=šta je?','"Nǎlǐ bù shūfu"=what wrong?',
    '"发烧"的意思？','Šta "fā shāo"?','What "fā shāo"?',['Kašalj','Temperatura','Glavobolja','Prehlada'],1,
    '中药(中医)很受欢迎：针灸、艾灸。','Zhongyi popularna: akupunktura.','TCM popular: acupuncture.',10],
  [44,44,'💊','在药店','Apoteka','At Pharmacy',
    [w('药店','yào diàn','Apoteka'),w('感冒','gǎn mào','Prehlada'),w('过敏','guò mǐn','Alergija'),w('止痛药','zhǐ tòng yào','Lek protiv bolova'),w('维生素','wéi shēng sù','Vitamin'),w('体温计','tǐ wēn jì','Termometar')],
    'A: 你好我感冒了。\nB: 有什么症状？\nA: 流鼻涕打喷嚏。\nB: 推荐这种药一天两次。','A: Zdravo prehlađen.\nB: Simptomi?\nA: Curi nos kijam.\nB: Ovaj lek 2x dnevno.','A: Hello have cold.\nB: Symptoms?\nA: Runny nose sneeze.\nB: This med twice daily.',
    '"一天两次/三次"表频率。"一次...片/粒"表剂量。','Doza: "yì tiān liǎng cì".','Dosage: "yì tiān liǎng cì".',
    '"一天两次"表示？','Šta "yì tiān liǎng cì"?','What "yì tiān liǎng cì"?',['1x dnevno','2x dnevno','3x dnevno','Svaki dan'],1,
    '中国药店连锁多。处方药需医生处方。','Apoteke lanci. Recept za jake lekove.','Pharmacy chains. Prescription needed.',10],
  [45,45,'🏦','在银行','Banka','At Bank',
    [w('银行','yín háng','Banka'),w('开户','kāi hù','Otvori račun'),w('换钱','huàn qián','Menjati'),w('汇率','huì lǜ','Kurs'),w('取钱','qǔ qián','Podići'),w('存款','cún kuǎn','Depozit')],
    'A: 我要换钱。\nB: 换什么？\nA: 欧元换人民币。今天汇率？\nB: 一欧元换七块八。','A: Menjam novac.\nB: Šta?\nA: Evre u juane. Kurs?\nB: 1 euro=7.8 juana.','A: Exchange money.\nB: What?\nA: Euros to RMB. Rate?\nB: 1 euro=7.8 yuan.',
    '"换"表兑换。"A换B"。','"Huàn"=menjati.','"Huàn"=exchange.',
    '"开户"的意思？','Šta "kāi hù"?','What "kāi hù"?',['Zatvoriti','Otvori račun','Menjati','Podići'],1,
    '外国人开户需护照。支付宝可绑外国卡。','Stranci trebaju pasoš. Alipay veže stranu karticu.','Foreigners need passport.',10],
  [46,46,'📮','在邮局','Pošta','At Post Office',
    [w('邮局','yóu jú','Pošta'),w('寄信','jì xìn','Poslati'),w('包裹','bāo guǒ','Paket'),w('邮票','yóu piào','Marka'),w('地址','dì zhǐ','Adresa'),w('快递','kuài dì','Ekspres')],
    'A: 我要寄包裹到塞尔维亚。\nB: 里面是什么？\nA: 礼物。空运要多久？\nB: 大概一周。','A: Šaljem paket u Srbiju.\nB: Šta unutra?\nA: Pokloni. Vazduhom?\nB: ~nedelju dana.','A: Send package to Serbia.\nB: What inside?\nA: Gifts. By air?\nB: ~1 week.',
    '"寄"+物品+"到"+地点。"要多久"问时间。','"Jì"+stvar+"dào"+mesto.','"Jì"+thing+"dào"+place.',
    '"快递"是什么？','Šta "kuài dì"?','What "kuài dì"?',['Sporo','Ekspres','Pismo','Marka'],1,
    '中国快递极快。顺丰圆通中通。同城当天到。','Kineska dostava brza. SF Express.','Chinese delivery very fast.',10],
  [47,47,'🎨','兴趣爱好（一）','Interesovanja(1)','Hobbies(1)',
    [w('喜欢','xǐ huān','Voleti'),w('唱歌','chàng gē','Pevati'),w('跳舞','tiào wǔ','Plesati'),w('画画','huà huà','Slikati'),w('弹钢琴','tán gāng qín','Svirati'),w('运动','yùn dòng','Sport')],
    'A: 你有什么爱好？\nB: 我喜欢唱歌跳舞。\nA: 喜欢什么运动？\nB: 打篮球。','A: Hobiji?\nB: Pevanje, ples.\nA: Sport?\nB: Košarka.','A: Hobbies?\nB: Sing, dance.\nA: Sport?\nB: Basketball.',
    '"爱好"=hobby。"喜欢"+动词/名词。"打"+球类。','"Xǐhuān"+glagol. "Dǎ"+loptu.','"Xǐhuān"+verb. "Dǎ"+ball.',
    '"弹钢琴"中"弹"表示？','Šta "tán"?','What "tán"?',['Baciti','Svirati','Gurati','Pevati'],1,
    'KTV非常流行。广场舞大妈最爱。乒乓球国球。','KTV popularan. Stoni tenis nacionalni.','KTV popular. Table tennis national.',10],
  [48,48,'🎨','兴趣爱好（二）','Interesovanja(2)','Hobbies(2)',
    [w('看书','kàn shū','Čitati'),w('看电影','kàn diàn yǐng','Filmovi'),w('旅行','lǚ xíng','Putovati'),w('摄影','shè yǐng','Fotografija'),w('玩游戏','wán yóu xì','Igrati'),w('做饭','zuò fàn','Kuvati')],
    'A: 你周末喜欢做什么？\nB: 喜欢看书和看电影。\nA: 喜欢看什么电影？\nB: 喜欢中国电影。','A: Vikend?\nB: Čitam, gledam filmove.\nA: Kakve filmove?\nB: Kineske.','A: Weekend?\nB: Read, watch movies.\nA: What movies?\nB: Chinese.',
    '"周末"=weekend。"喜欢的"=favorite。','"Zhōumò"=vikend.','"Zhōumò"=weekend.',
    '"旅行"的意思？','Šta "lǚ xíng"?','What "lǚ xíng"?',['Čitati','Putovati','Fotografisati','Kuvati'],1,
    '中国电影产业全球第二。张艺谋贾樟柯。','Kineski film 2. najveći. Zhang Yimou.','Chinese film 2nd largest.',10],
  [49,49,'💌','邀请和约会','Pozivi','Invitations',
    [w('邀请','yāo qǐng','Pozvati'),w('一起','yī qǐ','Zajedno'),w('有空','yǒu kòng','Imati vremena'),w('参加','cān jiā','Učestvovati'),w('聚会','jù huì','Žurka'),w('期待','qī dài','Radovati')],
    'A: 这周末你有空吗？\nB: 有空怎么了？\nA: 我想邀请你一起看电影。\nB: 好啊我很期待！','A: Vikend slobodan?\nB: Da.\nA: Pozivam te u bioskop.\nB: Super!','A: Free weekend?\nB: Yes.\nA: Invite you to movie.\nB: Great!',
    '"邀请+人+一起+动词"表邀请。"好啊！"表同意。','"Yāoqǐng"+osoba+"yìqǐ"+glagol.','"Yāoqǐng"+person+"yìqǐ"+verb.',
    '"有空"的意思？','Šta "yǒu kòng"?','What "yǒu kòng"?',['Zauzet','Imati vremena','Zabaviti','Raditi'],1,
    '"一起吃饭"是常见邀请。男通常付钱。','"Jedi zajedno" uobičajen poziv.','"Eat together" common invite.',10],
  [50,50,'📚','综合复习3','Pregled 3','Review 3',
    [w('复习','fù xí','Ponoviti'),w('巩固','gǒng gù','Učvrstiti'),w('实践','shí jiàn','Prakticirati'),w('应用','yìng yòng','Primeniti'),w('日常','rì cháng','Svakodnevno'),w('交流','jiāo liú','Razmena')],
    'A: 学了这些有什么感受？\nB: 我觉得可以买东西了！\nA: 多练习会更流利。\nB: 我会继续努力！','A: Nakon učenja?\nB: Mogu da kupujem!\nA: Vežbaj za tečnost.\nB: Nastaviću!','A: After learning?\nB: Can shop!\nA: Practice for fluency.\nB: Will continue!',
    '复习："请问""什么时候""哪里不舒服""有什么爱好"。','Ponavljanje: qǐngwèn, shénme shíhou.','Review: polite questions, time.',
    '"实践"的意思？','Šta "shí jiàn"?','What "shí jiàn"?',['Teorija','Praksa','Ponavljanje','Učenje'],1,
    '已能日常交流？找中国朋友练习进步最快。','Pričaj sa Kinezima za brzi napredak.','Speak with Chinese for fast progress.',15],
  [51,51,'🎉','节日庆祝（一）','Praznici(1)','Festivals(1)',
    [w('春节','chūn jié','Kineska Nova godina'),w('新年','xīn nián','Nova godina'),w('红包','hóng bāo','Crveni kovert'),w('饺子','jiǎo zi','Knedle'),w('团圆','tuán yuán','Okupljanje'),w('烟花','yān huā','Vatromet')],
    'A: 春节你做什么？\nB: 回家和父母团圆吃饺子。\nA: 收到红包了吗？\nB: 收到了很开心。','A: Za Kinesku Novu?\nB: Idem kući, jedemo knedle.\nA: Dobio crveni kovert?\nB: Da, srećan.','A: For Spring Festival?\nB: Go home, eat dumplings.\nA: Got red envelope?\nB: Yes, happy.',
    '"过年"=celebrate NY。"回家"=go home。"收到"=receive。','"Guò nián"=slaviti NG.','"Guò nián"=celebrate NY.',
    '"红包"里通常放什么？','Šta u "hóng bāo"?','What in "hóng bāo"?',['Bombone','Novac','Pismo','Poklon'],1,
    '春节最重要。除夕年夜饭看春晚。红包=压岁钱。','Kineska NG najvažniji praznik. Crveni koverti.','Spring Festival most important.',10],
  [52,52,'🎉','节日庆祝（二）','Praznici(2)','Festivals(2)',
    [w('中秋节','zhōng qiū jié','Festival sredine jeseni'),w('月饼','yuè bǐng','Mesečev kolač'),w('赏月','shǎng yuè','Diviti mesecu'),w('端午节','duān wǔ jié','Festival zmajevih čamaca'),w('粽子','zòng zi','Zongzi'),w('团圆','tuán yuán','Okupljanje')],
    'A: 中秋节到了吃月饼了吗？\nB: 吃了喜欢莲蓉月饼。\nA: 赏月了吗？\nB: 月亮很圆很漂亮。','A: Jeo mesečev kolač?\nB: Da, lotus pastu.\nA: Divio mesecu?\nB: Mesec pun i lep.','A: Eat mooncakes?\nB: Yes, lotus paste.\nA: Admire moon?\nB: Full and beautiful.',
    '"到了"表节日来临。"动词+了+吗？"问完成。','"Dào le"=stigao praznik.','"Dào le"=festival arrived.',
    '中秋节吃什么？','Šta jesti?','What to eat?',['饺子','月饼','粽子','汤圆'],1,
    '中秋农历八月十五。端午五月初五赛龙舟。','Zhongqiu 15.8 lunarni. Duanwu 5.5.','Mid-Autumn 15/8 lunar. Dragon Boat 5/5.',10],
  [53,53,'🙏','请求和帮助','Molbe i pomoć','Requests & Help',
    [w('帮助','bāng zhù','Pomoći'),w('可以','kě yǐ','Moći'),w('麻烦','má fan','Smetati'),w('谢谢帮助','xiè xiè bāng zhù','Hvala na pomoći'),w('不客气','bú kè qì','Nema na čemu'),w('需要','xū yào','Treba')],
    'A: 麻烦你可以帮我吗？\nB: 当然！需要什么？\nA: 帮我拿箱子。\nB: 没问题！\nA: 谢谢！\nB: 不客气！','A: Možeš pomoći?\nB: Naravno!\nA: Pomozi sa koferom.\nB: Nema problema!','A: Can you help?\nB: Of course!\nA: Help with box.\nB: No problem!',
    '"麻烦你"礼貌请求。"帮+我+动词"。','"Máfan nǐ"=izvinite. "Bāng wǒ"+glagol.','"Máfan nǐ"=sorry to bother.',
    '"不客气"的意思？','Šta "bú kè qì"?','What "bú kè qì"?',['Hvala','Nema na čemu','Izvinite','Molim'],1,
    '中国人乐于助人。拒绝时"不太方便"。','Kinezi rado pomažu. Odbijanje: "bù fāngbiàn".','Chinese helpful. Refusal indirect.',10],
  [54,54,'💭','表达感受','Osećanja','Feelings',
    [w('高兴','gāo xìng','Srećan'),w('难过','nán guò','Tužan'),w('生气','shēng qì','Ljut'),w('担心','dān xīn','Brinuti'),w('累','lèi','Umoran'),w('无聊','wú liáo','Dosadno')],
    'A: 你今天看起来不高兴怎么了？\nB: 我有点儿难过因为猫丢了。\nA: 别担心会找到的。\nB: 谢谢关心。','A: Izgledaš tužno.\nB: Malo tužna, izgubila mačku.\nA: Ne brini, naći će se.\nB: Hvala.','A: You look sad.\nB: Sad, lost cat.\nA: Don\'t worry, found.\nB: Thanks.',
    '"看起来"=looks like。"因为"表原因。"别+动词"祈使。','"Kàn qǐlái"=izgleda. "Bié+V"=nemoj.','"Kàn qǐlái"=looks. "Bié+V"=don\'t.',
    '"别担心"表示？','Šta "bié dān xīn"?','What "bié dān xīn"?',['Brinem','Ne brini','Tužan','Srećan'],1,
    '中国人表达含蓄。少说"我爱你"，多用行动。','Kinezi suzdržani. Akcije govore.','Chinese reserved. Actions speak.',10],
  [55,55,'⚖️','比较（一）','Poređenje(1)','Comparisons(1)',
    [w('比','bǐ','Od'),w('更','gèng','Još'),w('一样','yí yàng','Isto'),w('最','zuì','Naj'),w('差不多','chà bu duō','Otprilike'),w('不如','bù rú','Nije kao')],
    'A: 北京上海哪个更大？\nB: 北京比上海大。\nA: 哪个更热闹？\nB: 差不多。','A: Peking ili Šangaj veći?\nB: Peking veći.\nA: Življi?\nB: Otprilike isto.','A: Beijing or Shanghai bigger?\nB: Beijing bigger.\nA: Livelier?\nB: About same.',
    '"比"比较句：A+比+B+形容词。更=more，最=most。','"Bǐ"=od: A+bǐ+B+pridev.','"Bǐ"=than: A+bǐ+B+adj.',
    '"A比B大"中AB关系？','Odnos A i B?','Relationship A & B?',['A=B','A>B','A<B','A≠B'],1,
    '北京政治中心。上海经济中心。北上广三大城市。','Peking politički, Šangaj ekonomski.','Beijing political, Shanghai economic.',10],
  [56,56,'⚖️','比较（二）','Poređenje(2)','Comparisons(2)',
    [w('一样','yí yàng','Isto'),w('不同','bù tóng','Različito'),w('像','xiàng','Kao'),w('不如','bù rú','Nije tako'),w('越来越','yuè lái yuè','Sve više'),w('跟...一样','gēn...yí yàng','Isto kao')],
    'A: 中塞菜一样吗？\nB: 不一样中国菜更多样。\nA: 哪个更好吃？\nB: 都好吃越来越喜欢中国菜。','A: Kineska i srpska ista?\nB: Ne, kineska raznovrsnija.\nA: Ukusnija?\nB: Obe, sve više volim kinesku.','A: Chinese & Serbian same?\nB: No, Chinese diverse.\nA: Tastier?\nB: Both, increasingly like Chinese.',
    '"跟...一样"=same as。"越来越"+形容词=increasingly。','"Gēn...yíyàng"=isto kao.','"Gēn...yíyàng"=same as.',
    '"越来越"表什么趋势？','Šta "yuè lái yuè"?','What "yuè lái yuè"?',['Smanjenje','Povećanje','Isto','Povremeno'],1,
    '塞尔维亚ćevapi、sarma。中国饺子火锅。交换食谱。','Srpska hrana: ćevapi, sarma. Kineska: knedle.','Serbian: cevapi. Chinese: dumplings.',10],
  [57,57,'🔢','数字应用100-10000','Brojevi 100-10000','Numbers 100-10000',
    [w('百','bǎi','Sto'),w('千','qiān','Hiljada'),w('万','wàn','10.000'),w('一半','yí bàn','Pola'),w('百分之','bǎi fēn zhī','Procenat'),w('倍','bèi','Put(a)')],
    'A: 这手机多少钱？\nB: 五千九百九十九。\nA: 这么贵！去年才三千。\nB: 涨了快一倍。','A: Cena telefona?\nB: 5999.\nA: Skupo! Prošle 3000.\nB: Skoro duplo.','A: Phone price?\nB: 5999.\nA: Expensive! Last 3000.\nB: Almost doubled.',
    '十一(11)二十(20)一百一百一百(100)一千(1000)一万(10000)。','Brojevi: shíyī(11), èrshí(20).','Numbers: shíyī(11), èrshí(20).',
    '"一万"是多少？','Koliko "yí wàn"?','How much "yí wàn"?',['100','1000','10000','100000'],2,
    '汉语:万(10000)。百万=1,000,000。','Kineski: wàn(10.000). Milion=一百万.','Chinese: wàn(10,000).',10],
  [58,58,'📝','综合练习','Vežba','Practice',
    [w('练习','liàn xí','Vežba'),w('对话','duì huà','Dijalog'),w('角色扮演','jué sè bàn yǎn','Uloge'),w('情景','qíng jǐng','Scenarij'),w('实际','shí jì','Stvarno'),w('运用','yùn yòng','Primena')],
    'A: 我们来练习点菜吧！\nB: 好啊！我是服务员您要点什么？\nA: 宫保鸡丁和米饭。\nB: 喝什么？\nA: 茶。','A: Vežbajmo naručivanje!\nB: Ja konobar, šta?\nA: Kung Pao piletinu.\nB: Piće?\nA: Čaj.','A: Practice ordering!\nB: I\'m waiter, what?\nA: Kung Pao chicken.\nB: Drink?\nA: Tea.',
    '"来练习...吧"=let\'s practice。"一份"=one portion。','"Liànxí...ba"=vežbajmo. "Yí fèn"=porcija.','"Liànxí...ba"=let\'s practice.',
    '"一份"的意思？','Šta "yí fèn"?','What "yí fèn"?',['Porcija','Čaša','Vrsta','Tanjir'],0,
    '角色扮演学语言。勇敢开口不怕犯错！','Igranje uloga odlično za jezik. Ne boj se grešaka!','Role play great for language.',15],
  [59,59,'📚','阶段2复习','Pregled faze 2','Phase 2 Review',
    [w('复习','fù xí','Pregled'),w('总结','zǒng jié','Sumiranje'),w('熟练','shú liàn','Vešt'),w('自信','zì xìn','Samouveren'),w('交流','jiāo liú','Komunikacija'),w('进步','jìn bù','Napredak')],
    'A: 第二阶段快学完了感觉怎么样？\nB: 进步了很多！\nA: 可以自己去餐厅吗？\nB: 还学会讨价还价了。','A: Druga faza skoro gotova?\nB: Mnogo napredak!\nA: Možeš sam u restoran?\nB: I cenkanje naučio.','A: Phase 2 almost done?\nB: Much improvement!\nA: Can go restaurant alone?\nB: Learned bargaining too.',
    '复习："比"比较句、"越来越"、"从...到..."、数字。','Ponavljanje: bǐ, yuè lái yuè, brojevi.','Review: comparisons, increasingly, numbers.',
    '"自信"的意思？','Šta "zì xìn"?','What "zì xìn"?',['Samouveren','Srećan','Bistar','Vredan'],0,
    '能在很多场所用汉语交流了。很大成就！','Već možeš na kineskom u mnogim mestima!','Can communicate in Chinese in many places!',15],
  [60,60,'🎯','阶段2测试','Test faze 2','Phase 2 Test',
    [w('测试','cè shì','Test'),w('完成','wán chéng','Završiti'),w('优秀','yōu xiù','Odlično'),w('良好','liáng hǎo','Dobro'),w('继续努力','jì xù nǔ lì','Nastaviti'),w('祝贺','zhù hè','Čestitati')],
    'A: 通过测试了吗？\nB: 通过了！题目不难。\nA: 祝贺你！准备第三阶段吧。\nB: 好期待！','A: Položio test?\nB: Jesam! Nije teško.\nA: Čestitam! Spremi za 3.\nB: Jedva čekam!','A: Passed test?\nB: Yes! Not hard.\nA: Congrats! Prepare for 3.\nB: Looking forward!',
    '"通过"=pass。"不难"=not difficult。"准备"=prepare。','"Tōngguò"=proći. "Bù nán"=nije teško.','"Tōngguò"=pass. "Bù nán"=not hard.',
    '"祝贺"的意思？','Šta "zhù hè"?','What "zhù hè"?',['Pomoći','Čestitati','Ohrabriti','Slaviti'],1,
    '恭喜完成二阶段！下阶段学复杂社交话题。','Čestitam na 2. fazi! Sledeća: složenije teme.','Congrats on Phase 2! Next: complex topics.',20],
];

module.exports = { w, T, p2data };
