var fs=require('fs');
var data=JSON.parse(fs.readFileSync('dist/data/holidays.json','utf8'));
var E={};
function add(d,zh,sr,en){E[d]={zh:zh,sr:sr,en:en};}

add('2026-01-01','元旦是新年的第一天。Barry在北京和Anđela在贝尔格莱德有七小时时差，但午夜钟声响起时他们互相发送新年祝福。一个迎接新年的晨曦，一个倒数跨年钟声。距离让时间不同步，但心永远在同一个时区。','Nova Godina je prvi dan. Barry u Pekingu i Anđela u Kikindi dele sedam sati razlike — ali srca kucaju istim ritmom. Ljubav ne poznaje vremenske zone.','New Year\'s Day — Barry in Beijing and Anđela in Serbia share a seven-hour difference but their hearts beat as one. Love knows no time zones.');
add('2026-02-16','除夕是春节的前夜，全家吃年夜饭守岁。Barry给Anđela视频展示满桌的年夜饭。Anđela笑着说她学会了用筷子。除夕夜最温暖的时刻就是视频那头传来她的笑声。','Badnje veče kineske Nove Godine — porodica se okuplja uz bogatu večeru. Barry pokazuje Anđeli specijalitete. Anđela uči da koristi štapiće. Najlepši trenutak je njen smeh.','Lunar New Year\'s Eve — family dinner and staying up late. Barry shows Anđela the feast. She laughs learning chopsticks. Her laughter through the screen is the warmest gift.');
add('2026-04-05','清明节是祭祖扫墓的日子，也是踏青时节。人们清扫墓地献花烧纸钱。Barry说这是关于记忆的节日，正如塞尔维亚人在历史纪念日缅怀先人。虽然习俗不同，对逝去亲人的思念是一样的。','Qingming je dan sećanja na pretke. Ljudi čiste grobove. Barry kaže da je ovo praznik sećanja — kao što Srbi pamte svoje heroje. Isti osećaj, različiti običaji.','Qingming Festival honors ancestors by cleaning graves. Barry explains it\'s about remembrance — like Serbian memorial days. Different customs, same love for those gone.');
add('2026-05-01','劳动节在中国是七天长假，人们出行旅游。Barry和Anđela有自己的小传统：分享各自城市天空的照片。北京的天空和贝尔格莱德的天空其实相连的——就像思念飘过云层抵达对方。','Praznik rada u Kini je sedmodnevni odmor. Barry i Anđela dele fotografije neba. Ista plavetnilo ih povezuje — misli putuju oblacima jedno drugom.','Labor Day in China is a week-long holiday. Barry and Anđela share sky photos from their cities. The same blue connects them — thoughts travel through clouds.');
add('2026-08-19','七夕是中国传统情人节——牛郎织女隔着银河相望，每年鹊桥相会一次。Barry说这就是他们的故事——隔着七千公里，靠视频通话这座鹊桥每天相会。所爱隔山海，山海皆可平。','Qixi je kineski Dan zaljubljenih — legenda o pastiru i tkalji razdvojenim Mlečnim putem. Barry kaže da je to priča o njima — razdvojeni kilometrima, povezani ljubavlju.','Qixi is Chinese Valentine\'s Day — lovers separated by the Milky Way meet once yearly on a magpie bridge. Barry says this is their story — separated by distance but connected by love.');
add('2026-10-25','重阳节是登高望远敬老的日子。人们登高赏菊饮菊花酒。Barry给远方父母打电话，告诉Anđela要爱家人。Anđela说塞尔维亚也有类似传统——斯拉瓦，每个家庭守护神的纪念日。','Chongyang je dan poštovanja starijih. Ljudi se penju na planine. Barry i Anđela dele priče o porodičnim tradicijama — Chongyang i srpska Slava slave porodicu.','Double Ninth Festival honors elders. Barry and Anđela share family traditions — China\'s Chongyang and Serbia\'s Slava, both celebrating family and heritage.');
add('2026-09-10','教师节是尊师重教的体现。Barry说老师在中国如父母般受尊敬。Anđela说她最喜欢的塞尔维亚语文学老师教会她用文字表达爱。也许正是这些文字让她能写出给Barry最动人的情书。','Dan učitelja u Kini — učenici pokazuju zahvalnost. Anđelin omiljeni profesor srpskog jezika naučio ju je kako da izrazi ljubav rečima.','Teachers\' Day in China honors educators. Anđela\'s favorite Serbian literature teacher taught her to express love through words — the words she uses to write Barry\'s love letters.');
add('2026-05-01','塞尔维亚劳动节人们去郊外野餐烧烤。阳光草地和家人朋友。Barry说更喜欢塞尔维亚的版本——简单安静，如果Anđela在身边就完美了。','Praznik rada u Srbiji znači piknik i roštilj u prirodi. Barry više voli srpski način — jednostavno, tiho, savršeno kad je Anđela tu.','Serbia\'s Labor Day means picnics and barbecue outdoors. Barry prefers the Serbian version — simple, peaceful, perfect if Anđela is there.');
add('2026-05-09','胜利日纪念二战胜利。Barry和Anđela分享各自祖父的故事——Barry的爷爷参加过抗战，Anđela的祖父也是老兵。历史硝烟散去，和平的珍贵被两国共同铭记。','Dan pobede — kraj Drugog svetskog rata. Barry i Anđela dele priče o dedovima koji su ratovali. Iako na različitim stranama sveta, isti dan pobede ih povezuje.','Victory Day marks WWII\'s end. Barry and Anđela share grandfathers\' war stories. Though on different sides of the world, the same victory connects them.');
add('2026-11-11','停战日纪念一战结束。塞尔维亚在一战中损失巨大。Barry说中国也参与了一战，两国都是和平捍卫者。Anđela看着窗外落叶想着和平的珍贵和所爱之人的平安。','Dan primirja — kraj Prvog svetskog rata. Srbija je pretrpela ogromne gubitke. Anđela gleda kroz prozor i misli na mir i na one koje voli.','Armistice Day marks WWI\'s end. Serbia suffered tremendous losses. Anđela watches leaves fall, thinking of peace and those she loves.');
add('2026-02-14','情人节是全世界表达爱意的日子。Barry准备特别的礼物——用塞尔维亚语写的小诗或吉他弹唱。Anđela收到他手写的塞尔维亚语诗时哭了。最美的语言是他念她名字时的声音。','Dan zaljubljenih — Barry priprema pesmu na srpskom ili svirku na gitari. Anđela je plakala kad je dobila njegovu rukom pisanu pesmu. Najlepši jezik je zvuk njegovog glasa.','Valentine\'s Day — Barry prepares a Serbian poem or guitar song. Anđela cried at his handwritten poem. The most beautiful language is his voice saying her name.');
add('2026-03-08','妇女节在中国是半天假期和收礼物。Barry给妈妈和Anđela各送一束花。Anđela喜欢中国尊重女性的传统。两个国家都懂得女性的力量让世界更美好。','Dan žena — Barry šalje cveće majci i Anđeli. Dve kulture, isto poštovanje prema ženama koje čine svet lepšim.','Women\'s Day — Barry sends flowers to his mother and Anđela. Two cultures, same respect for women who make the world beautiful.');
add('2026-04-01','愚人节是开玩笑的日子。Barry曾骗Anđela买了去贝尔格莱德的机票——她激动了十分钟才发现是玩笑。但那一刻她眼中的期待让Barry发誓：总有一天这玩笑会成真。','Aprilski dani — Barry je prevario Anđelu da je kupio kartu za Beograd. Bila je uzbuđena deset minuta. Barry je obećao sebi: jednog dana, ovo će postati stvarno.','April Fools\' — Barry tricked Anđela about a Belgrade ticket. She was excited for ten minutes. Barry promised himself: one day, this will come true.');
add('2026-04-22','地球日提醒保护共同的家园。Barry和Anđela约定每年做一件环保小事——少用一个塑料袋、种一棵植物、关灯一小时。爱地球，也爱彼此。','Dan planete — Barry i Anđela svake godine urade nešto malo za planetu. Manje plastike, zasađena biljka, sat bez struje. Volimo Zemlju, volimo i jedno drugo.','Earth Day — Barry and Anđela do one small eco-friendly thing yearly. Less plastic, a planted seed, an hour without power. Love the Earth, love each other.');
add('2026-05-10','母亲节向母亲表达感谢。Barry给妈妈做了一顿饭。Anđela说塞尔维亚母亲节孩子们做手工礼物。两国方式不同但对母亲的爱一样。','Majčin dan — Barry je skuvao ručak mami. U Srbiji deca prave ručne radove. Različiti datumi, ista ljubav.','Mother\'s Day — Barry cooked for his mom. Serbian kids make handmade gifts. Same love, different ways.');
add('2026-05-15','国际家庭日提醒家庭的重要性。他们的家庭观念不同——中国注重团圆，塞尔维亚注重好客——但共同的愿望是组建跨越文化的小家庭。','Dan porodice — kineska porodica ceni okupljanje, srpska gostoljubivost. Oboje sanjaju porodicu koja spaja oba sveta.','Family Day — Chinese families value reunion, Serbian ones hospitality. They both dream of a family bridging both worlds.');
add('2026-06-01','儿童节是中国孩子们最期待的节日。Barry小时候最开心去游乐园。Anđela说塞尔维亚儿童节在秋天。孩子的笑容是全世界共通的语言。','Dečiji dan u Kini — Barry se seća zabavnog parka. U Srbiji se slavi u jesen. Dečiji osmesi su univerzalni.','Children\'s Day — Barry remembers amusement parks. Serbia celebrates in autumn. Children\'s smiles are universal.');
add('2026-06-21','父亲节感恩父亲。Barry陪父亲喝茶下棋——中国父爱含蓄深沉。Anđela说塞尔维亚父亲更热情会拥抱孩子。两种父爱同样深厚。','Dan očeva — Barry pije čaj sa ocem. Kineski očevi su suzdržani, srpski otvoreniji. Dva načina, ista ljubav.','Father\'s Day — Barry drinks tea with his dad. Chinese fathers are reserved, Serbian ones open. Two styles, same love.');
add('2026-10-31','万圣节在中国年轻人中越来越流行。Barry和Anđela分享各自的装扮照片。塞尔维亚城市也庆祝万圣节。戴上南瓜面具谁还看得出他们在恋爱？','Noć veštica — Barry i Anđela dele fotografije kostima. U Srbiji se takođe slavi. Pod maskom od bundeve niko ne vidi da su zaljubljeni.','Halloween — Barry and Anđela share costume photos. Serbian cities celebrate too. Behind pumpkin masks, no one can tell they\'re in love.');
add('2026-12-19','圣尼古拉节是塞尔维亚孩子最期待的日子——圣尼古拉给好孩子带礼物。Barry觉得像圣诞老人但更深具宗教意义。Anđela记得在靴子里找到糖果的喜悦。','Sveti Nikola — deca ostavljaju čizme i nalaze slatkiše. Barry kaže podseća na Deda Mraza ali dublji verski značaj. Anđela se seća radosti čokolade u čizmici.','St. Nicholas Day — children leave boots out for sweets. Barry notes resemblance to Santa but deeper meaning. Anđela remembers the joy of finding chocolate.');
add('2026-01-04','塞尔维亚父亲节在1月，中国在8月8日。Anđela笑着说一年庆祝两次给两位父亲双倍祝福。跨文化爱情连节日都是双份的。','Dan očeva u Srbiji — januar, u Kini 8. avgusta. Anđela se smeje — duplo više ljubavi za očeve. Ljubav koja spaja dve kulture donosi duple praznike.','Father\'s Day in January in Serbia, August 8 in China. Anđela laughs — double the love for their fathers. Cross-cultural love brings double holidays.');
add('2026-11-02','亡灵节是塞尔维亚纪念逝者的日子——扫墓点烛祈祷。和中国清明节非常相似。Barry和Anđela在这一天都给家人打电话珍惜当下。','Dušni dan — sećanje na preminule. Slično kineskom Qingmingu. Barry i Anđela zovu porodice da im kažu koliko ih vole.','All Souls\' Day — remembering the departed. Similar to China\'s Qingming. Barry and Anđela call their families to say I love you.');
add('2026-01-20','腊八节是春节序幕，人们喝腊八粥——八种食材熬制。每种食材有寓意。Anđela说八种食材就像八种爱的方式：温柔坚定想念等待理解包容守护和期待。','Laba festival uvodi Novu Godinu. Kaša od osam sastojaka — svaki ima značenje. Kao osam načina ljubavi: nežnost vera čežnja strpljenje razumevanje prihvatanje zaštita iščekivanje.','Laba Festival introduces New Year with eight-ingredient porridge. Eight ingredients like eight ways of loving: tenderness, faith, longing, patience, understanding, acceptance, protection, anticipation.');
add('2026-05-06','圣乔治节Đurđevdan标志着塞尔维亚春天的真正到来。人们用鲜花装饰家门年轻人唱歌跳舞。传说Đurđevdan清晨采摘的花朵能带来爱情好运。Anđela希望Barry能在这一天为她采一朵花。','Đurđevdan označava početak proleća. Kuće se kite cvećem. Legenda kaže da cveće ubrano u zoru donosi sreću u ljubavi. Anđela bi volela da joj Barry ubere cvet na Đurđevdan.','Đurđevdan marks spring\'s arrival in Serbia. Legend says flowers picked at dawn bring luck in love. Anđela wishes Barry could pick her a flower on this day.');
add('2026-07-12','圣彼得节Petrovdan是塞尔维亚重要的东正教节日，许多家庭庆祝Slava守护神日。用鱼和传统食物庆祝夏日的盛大节日。Barry隔着屏幕都能想象Anđela家满桌塞尔维亚美食的香味。','Petrovdan — praznik svetih Petra i Pavla. Mnoge porodice slave krsnu slavu uz ribu. Barry zamišlja trpezu punu srpskih specijaliteta i oseća toplinu Anđelinog doma.','St. Peter\'s Day honors Saints Peter and Paul. Many Serbian families celebrate their Slava with fish dishes. Barry imagines the table full of Serbian food and feels the warmth of Anđela\'s home.');
add('2026-08-28','圣母安息节纪念圣母玛利亚安息。东正教信徒前往教堂祈祷。Barry说这让他想起中国对母亲的尊重——无私的爱是相通的。Anđela相信圣母会保佑他们的远距离爱情。','Uspenje Bogorodice — vernici odlaze u crkvu. Barry kaže podseća na kinesko poštovanje majki. Anđela veruje da Bogorodica čuva njihovu ljubav.','Dormition of Mary — the faithful attend church. Barry says it parallels China\'s reverence for mothers. Anđela believes Mary watches over their long-distance love.');
add('2026-09-21','圣母圣诞日庆祝玛利亚诞生。东正教信徒特别敬拜圣母。Barry说中国虽无此节日但每人心中都有神圣的母亲形象。Anđela相信圣母理解他们分隔两地的思念。','Mala Gospojina — rođenje Bogorodice. Barry kaže u Kini nema ovaj praznik ali svi imaju svetu figuru majke. Anđela veruje Bogorodica razume njihovu ljubav.','Nativity of Mary — Orthodox believers venerate the Mother of God. Barry says China has no such feast but everyone carries a sacred mother figure in their heart.');
add('2026-05-20','520情人节——520谐音我爱你。Barry在午夜准时给Anđela发520红包附言不只是今天每一天都爱你。Anđela说是最甜蜜的数字情书。','520 — kineski Dan zaljubljenih. Broj 520 zvuči kao volim te. Barry je poslao 520 juana uz poruku "Ne samo danas". Anđela kaže najslađe ljubavno pismo.','520 Day — 520 sounds like "I love you" in Chinese. Barry sent 520 yuan with "Not just today." Anđela says it\'s the sweetest digital love letter.');
add('2026-11-11','双十一起源于中国大学校园的光棍节变成了全球最大购物节。Barry每年给Anđela买礼物——塞尔维亚红酒到中国茶叶。Anđela笑着说最好的礼物是每天能和他聊天。','11.11 — Dan samaca i najveći šoping praznik. Barry kupuje poklone za Anđelu. Njen najbolji poklon je svaki dan kada mogu da pričaju.','Singles\' Day (11.11) became the world\'s largest shopping day. Barry buys Anđela gifts. Her best gift is every day she gets to talk to him.');
add('2026-12-24','平安夜——塞尔维亚人准备圣诞晚宴装饰家庭。Barry每年视频帮Anđela装饰圣诞树。最温暖的平安夜礼物是看到她对镜头说Srećan Božić。','Badnje veče — Srbi pripremaju večeru. Barry pomaže Anđeli da kiti jelku preko video poziva. Najlepši poklon je njen osmeh dok peva božićnu pesmu.','Christmas Eve — Serbs prepare the festive dinner. Barry helps Anđela decorate the tree via video. The best gift is her smile singing a Christmas carol.');
add('2026-12-25','圣诞节（公历）——Barry和Anđela分享各自最喜欢的圣诞歌曲。他弹吉他录了Jingle Bells她唱塞尔维亚民歌。两种文化一个节日。','Božić (katolički) — Barry i Anđela razmenjuju božićne pesme. On svira gitaru, ona peva srpsku pesmu. Dve kulture, jedan praznik.','Christmas — Barry and Anđela exchange favorite carols. He plays guitar, she sings a Serbian song. Two cultures, one holiday.');
add('2026-12-31','跨年夜——Barry在北京Anđela在贝尔格莱德视频倒计时。午夜在北京是她在贝尔格莱德的黄昏。钟声敲响新年开始他们的故事继续。','Doček Nove Godine — Barry u Pekingu, Anđela u Kikindi. Sedam sati razlike. Kada u Pekingu zvoni ponoć, u Beogradu zalazi sunce. Nova godina, nova nada.','New Year\'s Eve — Beijing and Belgrade countdown with seven hours apart. Midnight in Beijing is sunset in Belgrade. New year, new hope, their story continues.');
add('2027-02-05','2027除夕——Barry和Anđela已经在视频中度过好几个除夕了。每一年感情更深距离更近。也许明年除夕他们不用隔着屏幕而是一起吃年夜饭。','Badnje veče 2027. Već nekoliko puta dočekali Novu Godinu preko video poziva. Svake godine bliži. Možda sledeće godine neće biti razdvojeni ekranom.','2027 New Year\'s Eve — several New Years via video call. Each year closer. Maybe next year, no screen between them.');
add('2027-02-06','2027鸡年——鸡象征勤奋和守信。Barry说Anđela就像鸡年出生的人一样诚实勇敢。她笑着说那她会每天早起给他打电话像公鸡打鸣一样准时。','2027 — godina petla. Petao simbolizuje marljivost. Barry kaže Anđela je hrabra i iskrena kao petao. Ona se smeje: budiću te svako jutro!','2027 Year of the Rooster — rooster symbolizes diligence. Barry says Anđela is brave and honest like a rooster. She laughs: I\'ll wake you every morning!');
add('2027-10-14','2027中秋——他们的异地恋又坚持了一年。月圆人未圆心却圆了。等见到她要带她吃最好的月饼喝最烈的rakija看最圆的月亮。等待越久重逢越美。','Festival sredine jeseni 2027. Još jedna godina ljubavi na daljinu. Mesec pun iako nisu zajedno. Kada se sretnu ješće najbolji mesečev kolač pod najpunijim mesecom.','2027 Mid-Autumn — another year of long-distance love endured. The moon is full though they\'re apart. When they meet, they\'ll share the best mooncake under the fullest moon.');

// Apply only where description is too short
var count=0;
Object.keys(E).forEach(function(d){
  var h=data.holidays.find(function(x){return x.d===d;});
  if(h && (!h.desc || !h.desc.zh || h.desc.zh.length<70)){
    h.desc={zh:E[d].zh,sr:E[d].sr,en:E[d].en};
    count++;
  }
});
console.log('Expanded:',count);

data.version='7.4.0';
fs.writeFileSync('dist/data/holidays.json',JSON.stringify(data,null,2),'utf8');

// Verify
var d2=JSON.parse(fs.readFileSync('dist/data/holidays.json','utf8'));
var bad=0;
d2.holidays.forEach(function(h){
  var zl=h.desc.zh?h.desc.zh.length:0;
  if(zl<70){bad++;console.log('SHORT:',h.d,h.name.zh||h.name.sr,'zh:'+zl);}
});
console.log('Total:',d2.holidays.length,'Below 70:',bad);
